import { useHome } from '../HomeContext';
import { useLanguage } from '../../../context/LanguageContext';
import SmartLink from '../../../components/SmartLink';

export default function IndustriesSection() {
  const { c, b, act, state } = useHome();
  const { t } = useLanguage();
  return (
    <>
      <section data-screen-label="Industries" className="ag" data-active-ind={state.indTab} style={{background: '#f7faff', borderTop: '1px solid #eef1f6', overflow: 'hidden'}}>
          <div style={{maxWidth: '1240px', margin: '0 auto', padding: '100px 32px'}}>
            <div data-reveal="0" style={{opacity: '0', transform: 'translateY(24px)', transition: 'all .7s cubic-bezier(.2,.7,.3,1)', display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center', gap: '14px'}}>
              <div style={{maxWidth: '780px'}}>
                <div style={{fontSize: '12.5px', fontWeight: '700', color: '#1a56db', letterSpacing: '1.6px', textTransform: 'uppercase'}}>{t("Who runs on Align")}</div>
                <h2 style={{fontSize: '46px', fontWeight: '800', letterSpacing: '-1.8px', margin: '14px 0 0', lineHeight: '1.06', textWrap: 'pretty'}}>{t("Different industries,")}<br /><span style={{background: 'linear-gradient(100deg,#1a56db 0%,#4b8bff 100%)', WebkitBackgroundClip: 'text', backgroundClip: 'text', color: 'transparent'}}>{t("the same discipline.")}</span></h2>
              </div>
              <SmartLink href="/industries.html" style={{fontSize: '15px', fontWeight: '600', color: '#1a56db', textDecoration: 'none', whiteSpace: 'nowrap'}}>{t("All industries →")}</SmartLink>
            </div>
      
            <div className="hm-stagger" style={{display: 'flex', flexWrap: 'wrap', justifyContent: 'center', gap: '10px', marginTop: '36px'}}>
                <button data-act="setInd0" onClick={() => act('setInd0')} style={{background: '#1a56db', color: '#ffffff', border: '1px solid #1a56db', borderRadius: '999px', padding: '9px 18px', fontSize: '13.5px', fontWeight: '600', cursor: 'pointer', transition: 'background .3s ease,color .3s ease,border-color .3s ease', whiteSpace: 'nowrap'}}>{t("Manufacturing")}</button>
                <button data-act="setInd1" onClick={() => act('setInd1')} style={{background: '#ffffff', color: '#5b6472', border: '1px solid #e4eaf3', borderRadius: '999px', padding: '9px 18px', fontSize: '13.5px', fontWeight: '600', cursor: 'pointer', transition: 'background .3s ease,color .3s ease,border-color .3s ease', whiteSpace: 'nowrap'}}>{t("Pharmaceutical")}</button>
                <button data-act="setInd2" onClick={() => act('setInd2')} style={{background: '#ffffff', color: '#5b6472', border: '1px solid #e4eaf3', borderRadius: '999px', padding: '9px 18px', fontSize: '13.5px', fontWeight: '600', cursor: 'pointer', transition: 'background .3s ease,color .3s ease,border-color .3s ease', whiteSpace: 'nowrap'}}>{t("Retail")}</button>
                <button data-act="setInd3" onClick={() => act('setInd3')} style={{background: '#ffffff', color: '#5b6472', border: '1px solid #e4eaf3', borderRadius: '999px', padding: '9px 18px', fontSize: '13.5px', fontWeight: '600', cursor: 'pointer', transition: 'background .3s ease,color .3s ease,border-color .3s ease', whiteSpace: 'nowrap'}}>{t("Distribution")}</button>
                <button data-act="setInd4" onClick={() => act('setInd4')} style={{background: '#ffffff', color: '#5b6472', border: '1px solid #e4eaf3', borderRadius: '999px', padding: '9px 18px', fontSize: '13.5px', fontWeight: '600', cursor: 'pointer', transition: 'background .3s ease,color .3s ease,border-color .3s ease', whiteSpace: 'nowrap'}}>{t("HR & Workforce")}</button>
                <button data-act="setInd5" onClick={() => act('setInd5')} style={{background: '#ffffff', color: '#5b6472', border: '1px solid #e4eaf3', borderRadius: '999px', padding: '9px 18px', fontSize: '13.5px', fontWeight: '600', cursor: 'pointer', transition: 'background .3s ease,color .3s ease,border-color .3s ease', whiteSpace: 'nowrap'}}>{t("Enterprise")}</button>
                <button data-act="setInd6" onClick={() => act('setInd6')} style={{background: '#ffffff', color: '#5b6472', border: '1px solid #e4eaf3', borderRadius: '999px', padding: '9px 18px', fontSize: '13.5px', fontWeight: '600', cursor: 'pointer', transition: 'background .3s ease,color .3s ease,border-color .3s ease', whiteSpace: 'nowrap'}}>{t("Services")}</button>
            </div>
      
            <div className="hm-indp-wrap" data-reveal="1" style={{opacity: '0', transform: 'translateY(24px)', transition: 'all .7s cubic-bezier(.2,.7,.3,1)', position: 'relative', height: '480px', marginTop: '28px'}}>
              <div style={{position: 'absolute', inset: '0', transition: 'opacity .6s ease,transform .6s cubic-bezier(.4,0,.2,1)', opacity: '1', transform: 'none', pointerEvents: 'auto'}} data-indp="0">
                <div style={{position: 'relative', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center'}}>
                  <div style={{position: 'relative', width: '70%', maxWidth: '660px', height: '430px', borderRadius: '20px', overflow: 'hidden', boxShadow: '0 44px 100px -40px rgba(26,86,219,.42)', border: '1px solid rgba(255,255,255,.6)', animation: 'floatY 8s ease-in-out infinite'}}>
                    <img src="/assets/images/industries/manufacturing.webp" loading="lazy" decoding="async" onError={(e) => { e.currentTarget.style.visibility = 'hidden'; }} alt={t("Manufacturing")} style={{width: '100%', height: '100%', objectFit: 'cover', display: 'block'}} />
                    <div style={{position: 'absolute', top: '16px', insetInlineStart: '16px', display: 'inline-flex', alignItems: 'center', gap: '8px', background: 'rgba(15,23,41,.5)', backdropFilter: 'blur(8px)', border: '1px solid rgba(255,255,255,.18)', borderRadius: '999px', padding: '7px 14px', zIndex: '4'}}><span style={{width: '8px', height: '8px', borderRadius: '50%', background: '#4b8bff', boxShadow: '0 0 0 3px rgba(75,139,255,.3)'}}></span><span style={{fontSize: '12px', fontWeight: '700', color: '#fff', letterSpacing: '.4px'}}>{t("Manufacturing")}</span></div>
                    <div style={{position: 'absolute', insetInlineEnd: '16px', bottom: '16px', width: '262px', background: 'linear-gradient(180deg,rgba(255,255,255,.98),rgba(246,250,255,.95))', backdropFilter: 'blur(16px) saturate(1.3)', border: '1px solid rgba(255,255,255,.95)', borderRadius: '20px', boxShadow: '0 34px 72px -22px rgba(26,86,219,.42),0 1px 0 rgba(255,255,255,.7) inset', padding: '16px 18px', animation: 'floatY 6.5s ease-in-out infinite', zIndex: '4'}}>
                      <div style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid #edf1f7', paddingBottom: '11px'}}><div style={{display: 'flex', alignItems: 'center', gap: '9px'}}><span style={{width: '26px', height: '26px', borderRadius: '9px', background: 'linear-gradient(135deg,#1a56db,#4b8bff)', display: 'grid', placeItems: 'center', color: '#fff', fontSize: '13px', fontWeight: '800', boxShadow: '0 7px 16px -5px rgba(26,86,219,.65)'}}>A</span><span style={{fontSize: '13.5px', fontWeight: '800', color: '#0f1729', letterSpacing: '-.3px'}}>Align</span></div><span style={{display: 'inline-flex', alignItems: 'center', gap: '5px', fontSize: '9px', fontWeight: '800', letterSpacing: '.6px', color: '#1a9d55', background: '#e3f6ec', borderRadius: '999px', padding: '4px 9px'}}><span style={{width: '6px', height: '6px', borderRadius: '50%', background: '#1a9d55', animation: 'pulseDot 2s ease-in-out infinite'}}></span>{t("LIVE")}</span></div><div style={{marginTop: '11px', position: 'relative'}}><svg viewBox="0 0 224 34" preserveAspectRatio="none" style={{width: '100%', height: '30px', display: 'block'}}><defs><linearGradient id="spk" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#4b8bff" stopOpacity=".26" /><stop offset="1" stopColor="#4b8bff" stopOpacity="0" /></linearGradient></defs><path d="M0,26 L24,20 L48,23 L72,14 L96,17 L120,9 L144,13 L168,6 L196,10 L224,3 L224,34 L0,34 Z" fill="url(#spk)"/><path d="M0,26 L24,20 L48,23 L72,14 L96,17 L120,9 L144,13 L168,6 L196,10 L224,3" fill="none" stroke="#1a56db" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" strokeDasharray="620" strokeDashoffset="620" style={{animation: 'spkDraw 2.4s cubic-bezier(.4,0,.2,1) forwards'}}/></svg><span style={{position: 'absolute', insetInlineEnd: '0', top: '1px', width: '6px', height: '6px', borderRadius: '50%', background: '#1a56db', boxShadow: '0 0 0 3px rgba(26,86,219,.18)'}}></span></div>
                      <div style={{fontSize: '11px', color: '#8a94a6', fontWeight: '600', marginTop: '9px', letterSpacing: '.2px'}}>{t("Production floor")}</div>
                      <div style={{display: 'flex', flexDirection: 'column', gap: '8px', marginTop: '9px'}}><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{fontSize: '10px', color: '#5b6472', width: '56px', flexShrink: '0'}}>{t("Coating")}</span><div style={{flex: '1', height: '6px', background: '#eef2fa', borderRadius: '99px', overflow: 'hidden'}}><div style={{width: '92%', height: '100%', background: '#1a56db', borderRadius: '99px', animation: 'ucCovA 5s ease-in-out infinite'}}></div></div></div><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{fontSize: '10px', color: '#5b6472', width: '56px', flexShrink: '0'}}>{t("Filling")}</span><div style={{flex: '1', height: '6px', background: '#eef2fa', borderRadius: '99px', overflow: 'hidden'}}><div style={{width: '86%', height: '100%', background: '#1a56db', borderRadius: '99px', animation: 'ucCovB 5s ease-in-out infinite'}}></div></div></div><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{fontSize: '10px', color: '#5b6472', width: '56px', flexShrink: '0'}}>{t("Sealing")}</span><div style={{flex: '1', height: '6px', background: '#eef2fa', borderRadius: '99px', overflow: 'hidden'}}><div style={{width: '71%', height: '100%', background: '#1a56db', borderRadius: '99px', animation: 'ucCovC 5s ease-in-out infinite'}}></div></div></div></div>
                      <div style={{marginTop: '11px', display: 'inline-flex', alignItems: 'center', gap: '6px', background: '#e3f6ec', borderRadius: '7px', padding: '5px 9px', fontSize: '10px', fontWeight: '700', color: '#1a9d55', animation: 'ucToast 5s ease-in-out infinite'}}>{t("＋ Batch #204 passed QC")}</div>
                    </div>
                  </div>
                  <div style={{position: 'absolute', insetInlineEnd: '11%', top: '15%', zIndex: '4'}}><div style={{background: 'rgba(255,255,255,.96)', backdropFilter: 'blur(10px)', border: '1px solid #eef1f6', borderRadius: '12px', padding: '10px 14px', boxShadow: '0 18px 40px -18px rgba(15,23,41,.3)', display: 'flex', alignItems: 'center', gap: '9px', whiteSpace: 'nowrap', cursor: 'default', animation: 'floatY 5s ease-in-out infinite', transition: 'transform .25s ease,box-shadow .25s ease'}} data-hv="hv-16"><span style={{width: '9px', height: '9px', borderRadius: '50%', background: '#1a9d55', flexShrink: '0', animation: 'pulseDot 2s ease-in-out infinite'}}></span><span style={{fontSize: '12.5px', fontWeight: '700', color: '#0f1729'}}>{t("Batch #204 — 82% yield")}</span></div></div>
                  <div style={{position: 'absolute', insetInlineStart: '11%', bottom: '19%', zIndex: '4'}}><div style={{background: 'rgba(255,255,255,.96)', backdropFilter: 'blur(10px)', border: '1px solid #eef1f6', borderRadius: '12px', padding: '10px 14px', boxShadow: '0 18px 40px -18px rgba(15,23,41,.3)', display: 'flex', alignItems: 'center', gap: '9px', whiteSpace: 'nowrap', cursor: 'default', animation: 'floatY2 5s ease-in-out infinite', transition: 'transform .25s ease,box-shadow .25s ease'}} data-hv="hv-16"><span style={{width: '9px', height: '9px', borderRadius: '50%', background: '#1a56db', flexShrink: '0', animation: 'pulseDot 2s ease-in-out infinite'}}></span><span style={{fontSize: '12.5px', fontWeight: '700', color: '#0f1729'}}>{t("Uptime 99.2%")}</span></div></div>
                </div>
              </div>
              <div style={{position: 'absolute', inset: '0', transition: 'opacity .6s ease,transform .6s cubic-bezier(.4,0,.2,1)', opacity: '0', transform: 'translateY(20px)', pointerEvents: 'none'}} data-indp="1">
                <div style={{position: 'relative', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center'}}>
                  <div style={{position: 'relative', width: '70%', maxWidth: '660px', height: '430px', borderRadius: '20px', overflow: 'hidden', boxShadow: '0 44px 100px -40px rgba(26,86,219,.42)', border: '1px solid rgba(255,255,255,.6)', animation: 'floatY 8s ease-in-out infinite'}}>
                    <img src="/assets/images/industries/pharma.webp" loading="lazy" decoding="async" onError={(e) => { e.currentTarget.style.visibility = 'hidden'; }} alt={t("Pharmaceutical")} style={{width: '100%', height: '100%', objectFit: 'cover', display: 'block'}} />
                    <div style={{position: 'absolute', top: '16px', insetInlineStart: '16px', display: 'inline-flex', alignItems: 'center', gap: '8px', background: 'rgba(15,23,41,.5)', backdropFilter: 'blur(8px)', border: '1px solid rgba(255,255,255,.18)', borderRadius: '999px', padding: '7px 14px', zIndex: '4'}}><span style={{width: '8px', height: '8px', borderRadius: '50%', background: '#4b8bff', boxShadow: '0 0 0 3px rgba(75,139,255,.3)'}}></span><span style={{fontSize: '12px', fontWeight: '700', color: '#fff', letterSpacing: '.4px'}}>{t("Pharmaceutical")}</span></div>
                    <div style={{position: 'absolute', insetInlineEnd: '16px', bottom: '16px', width: '262px', background: 'linear-gradient(180deg,rgba(255,255,255,.98),rgba(246,250,255,.95))', backdropFilter: 'blur(16px) saturate(1.3)', border: '1px solid rgba(255,255,255,.95)', borderRadius: '20px', boxShadow: '0 34px 72px -22px rgba(26,86,219,.42),0 1px 0 rgba(255,255,255,.7) inset', padding: '16px 18px', animation: 'floatY 6.5s ease-in-out infinite', zIndex: '4'}}>
                      <div style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid #edf1f7', paddingBottom: '11px'}}><div style={{display: 'flex', alignItems: 'center', gap: '9px'}}><span style={{width: '26px', height: '26px', borderRadius: '9px', background: 'linear-gradient(135deg,#1a56db,#4b8bff)', display: 'grid', placeItems: 'center', color: '#fff', fontSize: '13px', fontWeight: '800', boxShadow: '0 7px 16px -5px rgba(26,86,219,.65)'}}>A</span><span style={{fontSize: '13.5px', fontWeight: '800', color: '#0f1729', letterSpacing: '-.3px'}}>Align</span></div><span style={{display: 'inline-flex', alignItems: 'center', gap: '5px', fontSize: '9px', fontWeight: '800', letterSpacing: '.6px', color: '#1a9d55', background: '#e3f6ec', borderRadius: '999px', padding: '4px 9px'}}><span style={{width: '6px', height: '6px', borderRadius: '50%', background: '#1a9d55', animation: 'pulseDot 2s ease-in-out infinite'}}></span>{t("LIVE")}</span></div><div style={{marginTop: '11px', position: 'relative'}}><svg viewBox="0 0 224 34" preserveAspectRatio="none" style={{width: '100%', height: '30px', display: 'block'}}><defs><linearGradient id="spk" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#4b8bff" stopOpacity=".26" /><stop offset="1" stopColor="#4b8bff" stopOpacity="0" /></linearGradient></defs><path d="M0,26 L24,20 L48,23 L72,14 L96,17 L120,9 L144,13 L168,6 L196,10 L224,3 L224,34 L0,34 Z" fill="url(#spk)"/><path d="M0,26 L24,20 L48,23 L72,14 L96,17 L120,9 L144,13 L168,6 L196,10 L224,3" fill="none" stroke="#1a56db" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" strokeDasharray="620" strokeDashoffset="620" style={{animation: 'spkDraw 2.4s cubic-bezier(.4,0,.2,1) forwards'}}/></svg><span style={{position: 'absolute', insetInlineEnd: '0', top: '1px', width: '6px', height: '6px', borderRadius: '50%', background: '#1a56db', boxShadow: '0 0 0 3px rgba(26,86,219,.18)'}}></span></div>
                      <div style={{fontSize: '11px', color: '#8a94a6', fontWeight: '600', marginTop: '9px', letterSpacing: '.2px'}}>{t("Field coverage")}</div>
                      <div style={{display: 'flex', flexDirection: 'column', gap: '8px', marginTop: '9px'}}><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{fontSize: '10px', color: '#5b6472', width: '56px', flexShrink: '0'}}>{t("Karachi")}</span><div style={{flex: '1', height: '6px', background: '#eef2fa', borderRadius: '99px', overflow: 'hidden'}}><div style={{width: '92%', height: '100%', background: '#1a56db', borderRadius: '99px', animation: 'ucCovA 5s ease-in-out infinite'}}></div></div></div><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{fontSize: '10px', color: '#5b6472', width: '56px', flexShrink: '0'}}>{t("Lahore")}</span><div style={{flex: '1', height: '6px', background: '#eef2fa', borderRadius: '99px', overflow: 'hidden'}}><div style={{width: '86%', height: '100%', background: '#1a56db', borderRadius: '99px', animation: 'ucCovB 5s ease-in-out infinite'}}></div></div></div><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{fontSize: '10px', color: '#5b6472', width: '56px', flexShrink: '0'}}>{t("Multan")}</span><div style={{flex: '1', height: '6px', background: '#eef2fa', borderRadius: '99px', overflow: 'hidden'}}><div style={{width: '71%', height: '100%', background: '#1a56db', borderRadius: '99px', animation: 'ucCovC 5s ease-in-out infinite'}}></div></div></div></div>
                      <div style={{marginTop: '11px', display: 'inline-flex', alignItems: 'center', gap: '6px', background: '#e3f6ec', borderRadius: '7px', padding: '5px 9px', fontSize: '10px', fontWeight: '700', color: '#1a9d55', animation: 'ucToast 5s ease-in-out infinite'}}>{t("＋ Visit logged · Karachi")}</div>
                    </div>
                  </div>
                  <div style={{position: 'absolute', insetInlineEnd: '11%', top: '15%', zIndex: '4'}}><div style={{background: 'rgba(255,255,255,.96)', backdropFilter: 'blur(10px)', border: '1px solid #eef1f6', borderRadius: '12px', padding: '10px 14px', boxShadow: '0 18px 40px -18px rgba(15,23,41,.3)', display: 'flex', alignItems: 'center', gap: '9px', whiteSpace: 'nowrap', cursor: 'default', animation: 'floatY 5s ease-in-out infinite', transition: 'transform .25s ease,box-shadow .25s ease'}} data-hv="hv-16"><span style={{width: '9px', height: '9px', borderRadius: '50%', background: '#1a9d55', flexShrink: '0', animation: 'pulseDot 2s ease-in-out infinite'}}></span><span style={{fontSize: '12.5px', fontWeight: '700', color: '#0f1729'}}>{t("3 visits logged today")}</span></div></div>
                  <div style={{position: 'absolute', insetInlineStart: '11%', bottom: '19%', zIndex: '4'}}><div style={{background: 'rgba(255,255,255,.96)', backdropFilter: 'blur(10px)', border: '1px solid #eef1f6', borderRadius: '12px', padding: '10px 14px', boxShadow: '0 18px 40px -18px rgba(15,23,41,.3)', display: 'flex', alignItems: 'center', gap: '9px', whiteSpace: 'nowrap', cursor: 'default', animation: 'floatY2 5s ease-in-out infinite', transition: 'transform .25s ease,box-shadow .25s ease'}} data-hv="hv-16"><span style={{width: '9px', height: '9px', borderRadius: '50%', background: '#1a56db', flexShrink: '0', animation: 'pulseDot 2s ease-in-out infinite'}}></span><span style={{fontSize: '12.5px', fontWeight: '700', color: '#0f1729'}}>{t("Coverage 88%")}</span></div></div>
                </div>
              </div>
              <div style={{position: 'absolute', inset: '0', transition: 'opacity .6s ease,transform .6s cubic-bezier(.4,0,.2,1)', opacity: '0', transform: 'translateY(20px)', pointerEvents: 'none'}} data-indp="2">
                <div style={{position: 'relative', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center'}}>
                  <div style={{position: 'relative', width: '70%', maxWidth: '660px', height: '430px', borderRadius: '20px', overflow: 'hidden', boxShadow: '0 44px 100px -40px rgba(26,86,219,.42)', border: '1px solid rgba(255,255,255,.6)', animation: 'floatY 8s ease-in-out infinite'}}>
                    <img src="/assets/images/industries/retail.webp" loading="lazy" decoding="async" onError={(e) => { e.currentTarget.style.visibility = 'hidden'; }} alt={t("Retail")} style={{width: '100%', height: '100%', objectFit: 'cover', display: 'block'}} />
                    <div style={{position: 'absolute', top: '16px', insetInlineStart: '16px', display: 'inline-flex', alignItems: 'center', gap: '8px', background: 'rgba(15,23,41,.5)', backdropFilter: 'blur(8px)', border: '1px solid rgba(255,255,255,.18)', borderRadius: '999px', padding: '7px 14px', zIndex: '4'}}><span style={{width: '8px', height: '8px', borderRadius: '50%', background: '#4b8bff', boxShadow: '0 0 0 3px rgba(75,139,255,.3)'}}></span><span style={{fontSize: '12px', fontWeight: '700', color: '#fff', letterSpacing: '.4px'}}>{t("Retail")}</span></div>
                    <div style={{position: 'absolute', insetInlineEnd: '16px', bottom: '16px', width: '262px', background: 'linear-gradient(180deg,rgba(255,255,255,.98),rgba(246,250,255,.95))', backdropFilter: 'blur(16px) saturate(1.3)', border: '1px solid rgba(255,255,255,.95)', borderRadius: '20px', boxShadow: '0 34px 72px -22px rgba(26,86,219,.42),0 1px 0 rgba(255,255,255,.7) inset', padding: '16px 18px', animation: 'floatY 6.5s ease-in-out infinite', zIndex: '4'}}>
                      <div style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid #edf1f7', paddingBottom: '11px'}}><div style={{display: 'flex', alignItems: 'center', gap: '9px'}}><span style={{width: '26px', height: '26px', borderRadius: '9px', background: 'linear-gradient(135deg,#1a56db,#4b8bff)', display: 'grid', placeItems: 'center', color: '#fff', fontSize: '13px', fontWeight: '800', boxShadow: '0 7px 16px -5px rgba(26,86,219,.65)'}}>A</span><span style={{fontSize: '13.5px', fontWeight: '800', color: '#0f1729', letterSpacing: '-.3px'}}>Align</span></div><span style={{display: 'inline-flex', alignItems: 'center', gap: '5px', fontSize: '9px', fontWeight: '800', letterSpacing: '.6px', color: '#1a9d55', background: '#e3f6ec', borderRadius: '999px', padding: '4px 9px'}}><span style={{width: '6px', height: '6px', borderRadius: '50%', background: '#1a9d55', animation: 'pulseDot 2s ease-in-out infinite'}}></span>{t("LIVE")}</span></div><div style={{marginTop: '11px', position: 'relative'}}><svg viewBox="0 0 224 34" preserveAspectRatio="none" style={{width: '100%', height: '30px', display: 'block'}}><defs><linearGradient id="spk" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#4b8bff" stopOpacity=".26" /><stop offset="1" stopColor="#4b8bff" stopOpacity="0" /></linearGradient></defs><path d="M0,26 L24,20 L48,23 L72,14 L96,17 L120,9 L144,13 L168,6 L196,10 L224,3 L224,34 L0,34 Z" fill="url(#spk)"/><path d="M0,26 L24,20 L48,23 L72,14 L96,17 L120,9 L144,13 L168,6 L196,10 L224,3" fill="none" stroke="#1a56db" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" strokeDasharray="620" strokeDashoffset="620" style={{animation: 'spkDraw 2.4s cubic-bezier(.4,0,.2,1) forwards'}}/></svg><span style={{position: 'absolute', insetInlineEnd: '0', top: '1px', width: '6px', height: '6px', borderRadius: '50%', background: '#1a56db', boxShadow: '0 0 0 3px rgba(26,86,219,.18)'}}></span></div>
                      <div style={{fontSize: '11px', color: '#8a94a6', fontWeight: '600', marginTop: '9px', letterSpacing: '.2px'}}>{t("Store sales")}</div>
                      <div style={{display: 'flex', flexDirection: 'column', gap: '8px', marginTop: '9px'}}><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{fontSize: '10px', color: '#5b6472', width: '56px', flexShrink: '0'}}>{t("Store A")}</span><div style={{flex: '1', height: '6px', background: '#eef2fa', borderRadius: '99px', overflow: 'hidden'}}><div style={{width: '92%', height: '100%', background: '#1a56db', borderRadius: '99px', animation: 'ucCovA 5s ease-in-out infinite'}}></div></div></div><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{fontSize: '10px', color: '#5b6472', width: '56px', flexShrink: '0'}}>{t("Store B")}</span><div style={{flex: '1', height: '6px', background: '#eef2fa', borderRadius: '99px', overflow: 'hidden'}}><div style={{width: '86%', height: '100%', background: '#1a56db', borderRadius: '99px', animation: 'ucCovB 5s ease-in-out infinite'}}></div></div></div><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{fontSize: '10px', color: '#5b6472', width: '56px', flexShrink: '0'}}>{t("Store C")}</span><div style={{flex: '1', height: '6px', background: '#eef2fa', borderRadius: '99px', overflow: 'hidden'}}><div style={{width: '71%', height: '100%', background: '#1a56db', borderRadius: '99px', animation: 'ucCovC 5s ease-in-out infinite'}}></div></div></div></div>
                      <div style={{marginTop: '11px', display: 'inline-flex', alignItems: 'center', gap: '6px', background: '#e3f6ec', borderRadius: '7px', padding: '5px 9px', fontSize: '10px', fontWeight: '700', color: '#1a9d55', animation: 'ucToast 5s ease-in-out infinite'}}>{t("＋ Sale Rs 4,200 · POS 2")}</div>
                    </div>
                  </div>
                  <div style={{position: 'absolute', insetInlineEnd: '11%', top: '15%', zIndex: '4'}}><div style={{background: 'rgba(255,255,255,.96)', backdropFilter: 'blur(10px)', border: '1px solid #eef1f6', borderRadius: '12px', padding: '10px 14px', boxShadow: '0 18px 40px -18px rgba(15,23,41,.3)', display: 'flex', alignItems: 'center', gap: '9px', whiteSpace: 'nowrap', cursor: 'default', animation: 'floatY 5s ease-in-out infinite', transition: 'transform .25s ease,box-shadow .25s ease'}} data-hv="hv-16"><span style={{width: '9px', height: '9px', borderRadius: '50%', background: '#1a9d55', flexShrink: '0', animation: 'pulseDot 2s ease-in-out infinite'}}></span><span style={{fontSize: '12.5px', fontWeight: '700', color: '#0f1729'}}>{t("Sales Rs 245,000 ↗")}</span></div></div>
                  <div style={{position: 'absolute', insetInlineStart: '11%', bottom: '19%', zIndex: '4'}}><div style={{background: 'rgba(255,255,255,.96)', backdropFilter: 'blur(10px)', border: '1px solid #eef1f6', borderRadius: '12px', padding: '10px 14px', boxShadow: '0 18px 40px -18px rgba(15,23,41,.3)', display: 'flex', alignItems: 'center', gap: '9px', whiteSpace: 'nowrap', cursor: 'default', animation: 'floatY2 5s ease-in-out infinite', transition: 'transform .25s ease,box-shadow .25s ease'}} data-hv="hv-16"><span style={{width: '9px', height: '9px', borderRadius: '50%', background: '#b78103', flexShrink: '0', animation: 'pulseDot 2s ease-in-out infinite'}}></span><span style={{fontSize: '12.5px', fontWeight: '700', color: '#0f1729'}}>{t("Footfall +12%")}</span></div></div>
                </div>
              </div>
              <div style={{position: 'absolute', inset: '0', transition: 'opacity .6s ease,transform .6s cubic-bezier(.4,0,.2,1)', opacity: '0', transform: 'translateY(20px)', pointerEvents: 'none'}} data-indp="3">
                <div style={{position: 'relative', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center'}}>
                  <div style={{position: 'relative', width: '70%', maxWidth: '660px', height: '430px', borderRadius: '20px', overflow: 'hidden', boxShadow: '0 44px 100px -40px rgba(26,86,219,.42)', border: '1px solid rgba(255,255,255,.6)', animation: 'floatY 8s ease-in-out infinite'}}>
                    <img src="/assets/images/industries/distribution.webp" loading="lazy" decoding="async" onError={(e) => { e.currentTarget.style.visibility = 'hidden'; }} alt={t("Distribution")} style={{width: '100%', height: '100%', objectFit: 'cover', display: 'block'}} />
                    <div style={{position: 'absolute', top: '16px', insetInlineStart: '16px', display: 'inline-flex', alignItems: 'center', gap: '8px', background: 'rgba(15,23,41,.5)', backdropFilter: 'blur(8px)', border: '1px solid rgba(255,255,255,.18)', borderRadius: '999px', padding: '7px 14px', zIndex: '4'}}><span style={{width: '8px', height: '8px', borderRadius: '50%', background: '#4b8bff', boxShadow: '0 0 0 3px rgba(75,139,255,.3)'}}></span><span style={{fontSize: '12px', fontWeight: '700', color: '#fff', letterSpacing: '.4px'}}>{t("Distribution")}</span></div>
                    <div style={{position: 'absolute', insetInlineEnd: '16px', bottom: '16px', width: '262px', background: 'linear-gradient(180deg,rgba(255,255,255,.98),rgba(246,250,255,.95))', backdropFilter: 'blur(16px) saturate(1.3)', border: '1px solid rgba(255,255,255,.95)', borderRadius: '20px', boxShadow: '0 34px 72px -22px rgba(26,86,219,.42),0 1px 0 rgba(255,255,255,.7) inset', padding: '16px 18px', animation: 'floatY 6.5s ease-in-out infinite', zIndex: '4'}}>
                      <div style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid #edf1f7', paddingBottom: '11px'}}><div style={{display: 'flex', alignItems: 'center', gap: '9px'}}><span style={{width: '26px', height: '26px', borderRadius: '9px', background: 'linear-gradient(135deg,#1a56db,#4b8bff)', display: 'grid', placeItems: 'center', color: '#fff', fontSize: '13px', fontWeight: '800', boxShadow: '0 7px 16px -5px rgba(26,86,219,.65)'}}>A</span><span style={{fontSize: '13.5px', fontWeight: '800', color: '#0f1729', letterSpacing: '-.3px'}}>Align</span></div><span style={{display: 'inline-flex', alignItems: 'center', gap: '5px', fontSize: '9px', fontWeight: '800', letterSpacing: '.6px', color: '#1a9d55', background: '#e3f6ec', borderRadius: '999px', padding: '4px 9px'}}><span style={{width: '6px', height: '6px', borderRadius: '50%', background: '#1a9d55', animation: 'pulseDot 2s ease-in-out infinite'}}></span>{t("LIVE")}</span></div><div style={{marginTop: '11px', position: 'relative'}}><svg viewBox="0 0 224 34" preserveAspectRatio="none" style={{width: '100%', height: '30px', display: 'block'}}><defs><linearGradient id="spk" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#4b8bff" stopOpacity=".26" /><stop offset="1" stopColor="#4b8bff" stopOpacity="0" /></linearGradient></defs><path d="M0,26 L24,20 L48,23 L72,14 L96,17 L120,9 L144,13 L168,6 L196,10 L224,3 L224,34 L0,34 Z" fill="url(#spk)"/><path d="M0,26 L24,20 L48,23 L72,14 L96,17 L120,9 L144,13 L168,6 L196,10 L224,3" fill="none" stroke="#1a56db" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" strokeDasharray="620" strokeDashoffset="620" style={{animation: 'spkDraw 2.4s cubic-bezier(.4,0,.2,1) forwards'}}/></svg><span style={{position: 'absolute', insetInlineEnd: '0', top: '1px', width: '6px', height: '6px', borderRadius: '50%', background: '#1a56db', boxShadow: '0 0 0 3px rgba(26,86,219,.18)'}}></span></div>
                      <div style={{fontSize: '11px', color: '#8a94a6', fontWeight: '600', marginTop: '9px', letterSpacing: '.2px'}}>{t("Dispatch")}</div>
                      <div style={{display: 'flex', flexDirection: 'column', gap: '8px', marginTop: '9px'}}><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{fontSize: '10px', color: '#5b6472', width: '56px', flexShrink: '0'}}>{t("Loaded")}</span><div style={{flex: '1', height: '6px', background: '#eef2fa', borderRadius: '99px', overflow: 'hidden'}}><div style={{width: '92%', height: '100%', background: '#1a56db', borderRadius: '99px', animation: 'ucCovA 5s ease-in-out infinite'}}></div></div></div><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{fontSize: '10px', color: '#5b6472', width: '56px', flexShrink: '0'}}>{t("En route")}</span><div style={{flex: '1', height: '6px', background: '#eef2fa', borderRadius: '99px', overflow: 'hidden'}}><div style={{width: '86%', height: '100%', background: '#1a56db', borderRadius: '99px', animation: 'ucCovB 5s ease-in-out infinite'}}></div></div></div><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{fontSize: '10px', color: '#5b6472', width: '56px', flexShrink: '0'}}>{t("Delivered")}</span><div style={{flex: '1', height: '6px', background: '#eef2fa', borderRadius: '99px', overflow: 'hidden'}}><div style={{width: '71%', height: '100%', background: '#1a56db', borderRadius: '99px', animation: 'ucCovC 5s ease-in-out infinite'}}></div></div></div></div>
                      <div style={{marginTop: '11px', display: 'inline-flex', alignItems: 'center', gap: '6px', background: '#e3f6ec', borderRadius: '7px', padding: '5px 9px', fontSize: '10px', fontWeight: '700', color: '#1a9d55', animation: 'ucToast 5s ease-in-out infinite'}}>{t("＋ #4521 out for delivery")}</div>
                    </div>
                  </div>
                  <div style={{position: 'absolute', insetInlineEnd: '11%', top: '15%', zIndex: '4'}}><div style={{background: 'rgba(255,255,255,.96)', backdropFilter: 'blur(10px)', border: '1px solid #eef1f6', borderRadius: '12px', padding: '10px 14px', boxShadow: '0 18px 40px -18px rgba(15,23,41,.3)', display: 'flex', alignItems: 'center', gap: '9px', whiteSpace: 'nowrap', cursor: 'default', animation: 'floatY 5s ease-in-out infinite', transition: 'transform .25s ease,box-shadow .25s ease'}} data-hv="hv-16"><span style={{width: '9px', height: '9px', borderRadius: '50%', background: '#1a56db', flexShrink: '0', animation: 'pulseDot 2s ease-in-out infinite'}}></span><span style={{fontSize: '12.5px', fontWeight: '700', color: '#0f1729'}}>{t("Order #4521 · en route")}</span></div></div>
                  <div style={{position: 'absolute', insetInlineStart: '11%', bottom: '19%', zIndex: '4'}}><div style={{background: 'rgba(255,255,255,.96)', backdropFilter: 'blur(10px)', border: '1px solid #eef1f6', borderRadius: '12px', padding: '10px 14px', boxShadow: '0 18px 40px -18px rgba(15,23,41,.3)', display: 'flex', alignItems: 'center', gap: '9px', whiteSpace: 'nowrap', cursor: 'default', animation: 'floatY2 5s ease-in-out infinite', transition: 'transform .25s ease,box-shadow .25s ease'}} data-hv="hv-16"><span style={{width: '9px', height: '9px', borderRadius: '50%', background: '#1a9d55', flexShrink: '0', animation: 'pulseDot 2s ease-in-out infinite'}}></span><span style={{fontSize: '12.5px', fontWeight: '700', color: '#0f1729'}}>{t("On-time 96%")}</span></div></div>
                </div>
              </div>
              <div style={{position: 'absolute', inset: '0', transition: 'opacity .6s ease,transform .6s cubic-bezier(.4,0,.2,1)', opacity: '0', transform: 'translateY(20px)', pointerEvents: 'none'}} data-indp="4">
                <div style={{position: 'relative', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center'}}>
                  <div style={{position: 'relative', width: '70%', maxWidth: '660px', height: '430px', borderRadius: '20px', overflow: 'hidden', boxShadow: '0 44px 100px -40px rgba(26,86,219,.42)', border: '1px solid rgba(255,255,255,.6)', animation: 'floatY 8s ease-in-out infinite'}}>
                    <img src="/assets/images/industries/hr.webp" loading="lazy" decoding="async" onError={(e) => { e.currentTarget.style.visibility = 'hidden'; }} alt={t("HR & Workforce")} style={{width: '100%', height: '100%', objectFit: 'cover', display: 'block'}} />
                    <div style={{position: 'absolute', top: '16px', insetInlineStart: '16px', display: 'inline-flex', alignItems: 'center', gap: '8px', background: 'rgba(15,23,41,.5)', backdropFilter: 'blur(8px)', border: '1px solid rgba(255,255,255,.18)', borderRadius: '999px', padding: '7px 14px', zIndex: '4'}}><span style={{width: '8px', height: '8px', borderRadius: '50%', background: '#4b8bff', boxShadow: '0 0 0 3px rgba(75,139,255,.3)'}}></span><span style={{fontSize: '12px', fontWeight: '700', color: '#fff', letterSpacing: '.4px'}}>{t("HR & Workforce")}</span></div>
                    <div style={{position: 'absolute', insetInlineEnd: '16px', bottom: '16px', width: '262px', background: 'linear-gradient(180deg,rgba(255,255,255,.98),rgba(246,250,255,.95))', backdropFilter: 'blur(16px) saturate(1.3)', border: '1px solid rgba(255,255,255,.95)', borderRadius: '20px', boxShadow: '0 34px 72px -22px rgba(26,86,219,.42),0 1px 0 rgba(255,255,255,.7) inset', padding: '16px 18px', animation: 'floatY 6.5s ease-in-out infinite', zIndex: '4'}}>
                      <div style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid #edf1f7', paddingBottom: '11px'}}><div style={{display: 'flex', alignItems: 'center', gap: '9px'}}><span style={{width: '26px', height: '26px', borderRadius: '9px', background: 'linear-gradient(135deg,#1a56db,#4b8bff)', display: 'grid', placeItems: 'center', color: '#fff', fontSize: '13px', fontWeight: '800', boxShadow: '0 7px 16px -5px rgba(26,86,219,.65)'}}>A</span><span style={{fontSize: '13.5px', fontWeight: '800', color: '#0f1729', letterSpacing: '-.3px'}}>Align</span></div><span style={{display: 'inline-flex', alignItems: 'center', gap: '5px', fontSize: '9px', fontWeight: '800', letterSpacing: '.6px', color: '#1a9d55', background: '#e3f6ec', borderRadius: '999px', padding: '4px 9px'}}><span style={{width: '6px', height: '6px', borderRadius: '50%', background: '#1a9d55', animation: 'pulseDot 2s ease-in-out infinite'}}></span>{t("LIVE")}</span></div><div style={{marginTop: '11px', position: 'relative'}}><svg viewBox="0 0 224 34" preserveAspectRatio="none" style={{width: '100%', height: '30px', display: 'block'}}><defs><linearGradient id="spk" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#4b8bff" stopOpacity=".26" /><stop offset="1" stopColor="#4b8bff" stopOpacity="0" /></linearGradient></defs><path d="M0,26 L24,20 L48,23 L72,14 L96,17 L120,9 L144,13 L168,6 L196,10 L224,3 L224,34 L0,34 Z" fill="url(#spk)"/><path d="M0,26 L24,20 L48,23 L72,14 L96,17 L120,9 L144,13 L168,6 L196,10 L224,3" fill="none" stroke="#1a56db" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" strokeDasharray="620" strokeDashoffset="620" style={{animation: 'spkDraw 2.4s cubic-bezier(.4,0,.2,1) forwards'}}/></svg><span style={{position: 'absolute', insetInlineEnd: '0', top: '1px', width: '6px', height: '6px', borderRadius: '50%', background: '#1a56db', boxShadow: '0 0 0 3px rgba(26,86,219,.18)'}}></span></div>
                      <div style={{fontSize: '11px', color: '#8a94a6', fontWeight: '600', marginTop: '9px', letterSpacing: '.2px'}}>{t("Attendance")}</div>
                      <div style={{display: 'flex', flexDirection: 'column', gap: '8px', marginTop: '9px'}}><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{fontSize: '10px', color: '#5b6472', width: '56px', flexShrink: '0'}}>{t("Present")}</span><div style={{flex: '1', height: '6px', background: '#eef2fa', borderRadius: '99px', overflow: 'hidden'}}><div style={{width: '92%', height: '100%', background: '#1a56db', borderRadius: '99px', animation: 'ucCovA 5s ease-in-out infinite'}}></div></div></div><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{fontSize: '10px', color: '#5b6472', width: '56px', flexShrink: '0'}}>{t("Remote")}</span><div style={{flex: '1', height: '6px', background: '#eef2fa', borderRadius: '99px', overflow: 'hidden'}}><div style={{width: '86%', height: '100%', background: '#1a56db', borderRadius: '99px', animation: 'ucCovB 5s ease-in-out infinite'}}></div></div></div><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{fontSize: '10px', color: '#5b6472', width: '56px', flexShrink: '0'}}>{t("Leave")}</span><div style={{flex: '1', height: '6px', background: '#eef2fa', borderRadius: '99px', overflow: 'hidden'}}><div style={{width: '71%', height: '100%', background: '#1a56db', borderRadius: '99px', animation: 'ucCovC 5s ease-in-out infinite'}}></div></div></div></div>
                      <div style={{marginTop: '11px', display: 'inline-flex', alignItems: 'center', gap: '6px', background: '#e3f6ec', borderRadius: '7px', padding: '5px 9px', fontSize: '10px', fontWeight: '700', color: '#1a9d55', animation: 'ucToast 5s ease-in-out infinite'}}>{t("＋ 12 clock-ins · 9:01")}</div>
                    </div>
                  </div>
                  <div style={{position: 'absolute', insetInlineEnd: '11%', top: '15%', zIndex: '4'}}><div style={{background: 'rgba(255,255,255,.96)', backdropFilter: 'blur(10px)', border: '1px solid #eef1f6', borderRadius: '12px', padding: '10px 14px', boxShadow: '0 18px 40px -18px rgba(15,23,41,.3)', display: 'flex', alignItems: 'center', gap: '9px', whiteSpace: 'nowrap', cursor: 'default', animation: 'floatY 5s ease-in-out infinite', transition: 'transform .25s ease,box-shadow .25s ease'}} data-hv="hv-16"><span style={{width: '9px', height: '9px', borderRadius: '50%', background: '#1a9d55', flexShrink: '0', animation: 'pulseDot 2s ease-in-out infinite'}}></span><span style={{fontSize: '12.5px', fontWeight: '700', color: '#0f1729'}}>{t("Present today 94%")}</span></div></div>
                  <div style={{position: 'absolute', insetInlineStart: '11%', bottom: '19%', zIndex: '4'}}><div style={{background: 'rgba(255,255,255,.96)', backdropFilter: 'blur(10px)', border: '1px solid #eef1f6', borderRadius: '12px', padding: '10px 14px', boxShadow: '0 18px 40px -18px rgba(15,23,41,.3)', display: 'flex', alignItems: 'center', gap: '9px', whiteSpace: 'nowrap', cursor: 'default', animation: 'floatY2 5s ease-in-out infinite', transition: 'transform .25s ease,box-shadow .25s ease'}} data-hv="hv-16"><span style={{width: '9px', height: '9px', borderRadius: '50%', background: '#1a56db', flexShrink: '0', animation: 'pulseDot 2s ease-in-out infinite'}}></span><span style={{fontSize: '12.5px', fontWeight: '700', color: '#0f1729'}}>{t("Payroll ready to run")}</span></div></div>
                </div>
              </div>
              <div style={{position: 'absolute', inset: '0', transition: 'opacity .6s ease,transform .6s cubic-bezier(.4,0,.2,1)', opacity: '0', transform: 'translateY(20px)', pointerEvents: 'none'}} data-indp="5">
                <div style={{position: 'relative', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center'}}>
                  <div style={{position: 'relative', width: '70%', maxWidth: '660px', height: '430px', borderRadius: '20px', overflow: 'hidden', boxShadow: '0 44px 100px -40px rgba(26,86,219,.42)', border: '1px solid rgba(255,255,255,.6)', animation: 'floatY 8s ease-in-out infinite'}}>
                    <img src="/assets/images/industries/enterprise.webp" loading="lazy" decoding="async" onError={(e) => { e.currentTarget.style.visibility = 'hidden'; }} alt={t("Enterprise")} style={{width: '100%', height: '100%', objectFit: 'cover', display: 'block'}} />
                    <div style={{position: 'absolute', top: '16px', insetInlineStart: '16px', display: 'inline-flex', alignItems: 'center', gap: '8px', background: 'rgba(15,23,41,.5)', backdropFilter: 'blur(8px)', border: '1px solid rgba(255,255,255,.18)', borderRadius: '999px', padding: '7px 14px', zIndex: '4'}}><span style={{width: '8px', height: '8px', borderRadius: '50%', background: '#4b8bff', boxShadow: '0 0 0 3px rgba(75,139,255,.3)'}}></span><span style={{fontSize: '12px', fontWeight: '700', color: '#fff', letterSpacing: '.4px'}}>{t("Enterprise")}</span></div>
                    <div style={{position: 'absolute', insetInlineEnd: '16px', bottom: '16px', width: '262px', background: 'linear-gradient(180deg,rgba(255,255,255,.98),rgba(246,250,255,.95))', backdropFilter: 'blur(16px) saturate(1.3)', border: '1px solid rgba(255,255,255,.95)', borderRadius: '20px', boxShadow: '0 34px 72px -22px rgba(26,86,219,.42),0 1px 0 rgba(255,255,255,.7) inset', padding: '16px 18px', animation: 'floatY 6.5s ease-in-out infinite', zIndex: '4'}}>
                      <div style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid #edf1f7', paddingBottom: '11px'}}><div style={{display: 'flex', alignItems: 'center', gap: '9px'}}><span style={{width: '26px', height: '26px', borderRadius: '9px', background: 'linear-gradient(135deg,#1a56db,#4b8bff)', display: 'grid', placeItems: 'center', color: '#fff', fontSize: '13px', fontWeight: '800', boxShadow: '0 7px 16px -5px rgba(26,86,219,.65)'}}>A</span><span style={{fontSize: '13.5px', fontWeight: '800', color: '#0f1729', letterSpacing: '-.3px'}}>Align Suite</span></div><span style={{display: 'inline-flex', alignItems: 'center', gap: '5px', fontSize: '9px', fontWeight: '800', letterSpacing: '.6px', color: '#1a9d55', background: '#e3f6ec', borderRadius: '999px', padding: '4px 9px'}}><span style={{width: '6px', height: '6px', borderRadius: '50%', background: '#1a9d55', animation: 'pulseDot 2s ease-in-out infinite'}}></span>{t("LIVE")}</span></div><div style={{marginTop: '11px', position: 'relative'}}><svg viewBox="0 0 224 34" preserveAspectRatio="none" style={{width: '100%', height: '30px', display: 'block'}}><defs><linearGradient id="spk" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#4b8bff" stopOpacity=".26" /><stop offset="1" stopColor="#4b8bff" stopOpacity="0" /></linearGradient></defs><path d="M0,26 L24,20 L48,23 L72,14 L96,17 L120,9 L144,13 L168,6 L196,10 L224,3 L224,34 L0,34 Z" fill="url(#spk)"/><path d="M0,26 L24,20 L48,23 L72,14 L96,17 L120,9 L144,13 L168,6 L196,10 L224,3" fill="none" stroke="#1a56db" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" strokeDasharray="620" strokeDashoffset="620" style={{animation: 'spkDraw 2.4s cubic-bezier(.4,0,.2,1) forwards'}}/></svg><span style={{position: 'absolute', insetInlineEnd: '0', top: '1px', width: '6px', height: '6px', borderRadius: '50%', background: '#1a56db', boxShadow: '0 0 0 3px rgba(26,86,219,.18)'}}></span></div>
                      <div style={{fontSize: '11px', color: '#8a94a6', fontWeight: '600', marginTop: '9px', letterSpacing: '.2px'}}>{t("Group KPIs")}</div>
                      <div style={{display: 'flex', flexDirection: 'column', gap: '8px', marginTop: '9px'}}><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{fontSize: '10px', color: '#5b6472', width: '56px', flexShrink: '0'}}>{t("Revenue")}</span><div style={{flex: '1', height: '6px', background: '#eef2fa', borderRadius: '99px', overflow: 'hidden'}}><div style={{width: '92%', height: '100%', background: '#1a56db', borderRadius: '99px', animation: 'ucCovA 5s ease-in-out infinite'}}></div></div></div><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{fontSize: '10px', color: '#5b6472', width: '56px', flexShrink: '0'}}>{t("Margin")}</span><div style={{flex: '1', height: '6px', background: '#eef2fa', borderRadius: '99px', overflow: 'hidden'}}><div style={{width: '86%', height: '100%', background: '#1a56db', borderRadius: '99px', animation: 'ucCovB 5s ease-in-out infinite'}}></div></div></div><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{fontSize: '10px', color: '#5b6472', width: '56px', flexShrink: '0'}}>{t("Cash")}</span><div style={{flex: '1', height: '6px', background: '#eef2fa', borderRadius: '99px', overflow: 'hidden'}}><div style={{width: '71%', height: '100%', background: '#1a56db', borderRadius: '99px', animation: 'ucCovC 5s ease-in-out infinite'}}></div></div></div></div>
                      <div style={{marginTop: '11px', display: 'inline-flex', alignItems: 'center', gap: '6px', background: '#e3f6ec', borderRadius: '7px', padding: '5px 9px', fontSize: '10px', fontWeight: '700', color: '#1a9d55', animation: 'ucToast 5s ease-in-out infinite'}}>{t("＋ Month-end closed")}</div>
                    </div>
                  </div>
                  <div style={{position: 'absolute', insetInlineEnd: '11%', top: '15%', zIndex: '4'}}><div style={{background: 'rgba(255,255,255,.96)', backdropFilter: 'blur(10px)', border: '1px solid #eef1f6', borderRadius: '12px', padding: '10px 14px', boxShadow: '0 18px 40px -18px rgba(15,23,41,.3)', display: 'flex', alignItems: 'center', gap: '9px', whiteSpace: 'nowrap', cursor: 'default', animation: 'floatY 5s ease-in-out infinite', transition: 'transform .25s ease,box-shadow .25s ease'}} data-hv="hv-16"><span style={{width: '9px', height: '9px', borderRadius: '50%', background: '#1a9d55', flexShrink: '0', animation: 'pulseDot 2s ease-in-out infinite'}}></span><span style={{fontSize: '12.5px', fontWeight: '700', color: '#0f1729'}}>{t("Revenue +18% QoQ")}</span></div></div>
                  <div style={{position: 'absolute', insetInlineStart: '11%', bottom: '19%', zIndex: '4'}}><div style={{background: 'rgba(255,255,255,.96)', backdropFilter: 'blur(10px)', border: '1px solid #eef1f6', borderRadius: '12px', padding: '10px 14px', boxShadow: '0 18px 40px -18px rgba(15,23,41,.3)', display: 'flex', alignItems: 'center', gap: '9px', whiteSpace: 'nowrap', cursor: 'default', animation: 'floatY2 5s ease-in-out infinite', transition: 'transform .25s ease,box-shadow .25s ease'}} data-hv="hv-16"><span style={{width: '9px', height: '9px', borderRadius: '50%', background: '#1a56db', flexShrink: '0', animation: 'pulseDot 2s ease-in-out infinite'}}></span><span style={{fontSize: '12.5px', fontWeight: '700', color: '#0f1729'}}>{t("3 products · 1 login")}</span></div></div>
                </div>
              </div>
              <div style={{position: 'absolute', inset: '0', transition: 'opacity .6s ease,transform .6s cubic-bezier(.4,0,.2,1)', opacity: '0', transform: 'translateY(20px)', pointerEvents: 'none'}} data-indp="6">
                <div style={{position: 'relative', height: '100%', display: 'flex', alignItems: 'center', justifyContent: 'center'}}>
                  <div style={{position: 'relative', width: '70%', maxWidth: '660px', height: '430px', borderRadius: '20px', overflow: 'hidden', boxShadow: '0 44px 100px -40px rgba(26,86,219,.42)', border: '1px solid rgba(255,255,255,.6)', animation: 'floatY 8s ease-in-out infinite'}}>
                    <img src="/assets/images/industries/services.webp" loading="lazy" decoding="async" onError={(e) => { e.currentTarget.style.visibility = 'hidden'; }} alt={t("Services")} style={{width: '100%', height: '100%', objectFit: 'cover', display: 'block'}} />
                    <div style={{position: 'absolute', top: '16px', insetInlineStart: '16px', display: 'inline-flex', alignItems: 'center', gap: '8px', background: 'rgba(15,23,41,.5)', backdropFilter: 'blur(8px)', border: '1px solid rgba(255,255,255,.18)', borderRadius: '999px', padding: '7px 14px', zIndex: '4'}}><span style={{width: '8px', height: '8px', borderRadius: '50%', background: '#4b8bff', boxShadow: '0 0 0 3px rgba(75,139,255,.3)'}}></span><span style={{fontSize: '12px', fontWeight: '700', color: '#fff', letterSpacing: '.4px'}}>{t("Services")}</span></div>
                    <div style={{position: 'absolute', insetInlineEnd: '16px', bottom: '16px', width: '262px', background: 'linear-gradient(180deg,rgba(255,255,255,.98),rgba(246,250,255,.95))', backdropFilter: 'blur(16px) saturate(1.3)', border: '1px solid rgba(255,255,255,.95)', borderRadius: '20px', boxShadow: '0 34px 72px -22px rgba(26,86,219,.42),0 1px 0 rgba(255,255,255,.7) inset', padding: '16px 18px', animation: 'floatY 6.5s ease-in-out infinite', zIndex: '4'}}>
                      <div style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '1px solid #edf1f7', paddingBottom: '11px'}}><div style={{display: 'flex', alignItems: 'center', gap: '9px'}}><span style={{width: '26px', height: '26px', borderRadius: '9px', background: 'linear-gradient(135deg,#1a56db,#4b8bff)', display: 'grid', placeItems: 'center', color: '#fff', fontSize: '13px', fontWeight: '800', boxShadow: '0 7px 16px -5px rgba(26,86,219,.65)'}}>A</span><span style={{fontSize: '13.5px', fontWeight: '800', color: '#0f1729', letterSpacing: '-.3px'}}>Align</span></div><span style={{display: 'inline-flex', alignItems: 'center', gap: '5px', fontSize: '9px', fontWeight: '800', letterSpacing: '.6px', color: '#1a9d55', background: '#e3f6ec', borderRadius: '999px', padding: '4px 9px'}}><span style={{width: '6px', height: '6px', borderRadius: '50%', background: '#1a9d55', animation: 'pulseDot 2s ease-in-out infinite'}}></span>{t("LIVE")}</span></div><div style={{marginTop: '11px', position: 'relative'}}><svg viewBox="0 0 224 34" preserveAspectRatio="none" style={{width: '100%', height: '30px', display: 'block'}}><defs><linearGradient id="spk" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#4b8bff" stopOpacity=".26" /><stop offset="1" stopColor="#4b8bff" stopOpacity="0" /></linearGradient></defs><path d="M0,26 L24,20 L48,23 L72,14 L96,17 L120,9 L144,13 L168,6 L196,10 L224,3 L224,34 L0,34 Z" fill="url(#spk)"/><path d="M0,26 L24,20 L48,23 L72,14 L96,17 L120,9 L144,13 L168,6 L196,10 L224,3" fill="none" stroke="#1a56db" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" strokeDasharray="620" strokeDashoffset="620" style={{animation: 'spkDraw 2.4s cubic-bezier(.4,0,.2,1) forwards'}}/></svg><span style={{position: 'absolute', insetInlineEnd: '0', top: '1px', width: '6px', height: '6px', borderRadius: '50%', background: '#1a56db', boxShadow: '0 0 0 3px rgba(26,86,219,.18)'}}></span></div>
                      <div style={{fontSize: '11px', color: '#8a94a6', fontWeight: '600', marginTop: '9px', letterSpacing: '.2px'}}>{t("Projects")}</div>
                      <div style={{display: 'flex', flexDirection: 'column', gap: '8px', marginTop: '9px'}}><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{fontSize: '10px', color: '#5b6472', width: '56px', flexShrink: '0'}}>{t("Billable")}</span><div style={{flex: '1', height: '6px', background: '#eef2fa', borderRadius: '99px', overflow: 'hidden'}}><div style={{width: '92%', height: '100%', background: '#1a56db', borderRadius: '99px', animation: 'ucCovA 5s ease-in-out infinite'}}></div></div></div><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{fontSize: '10px', color: '#5b6472', width: '56px', flexShrink: '0'}}>{t("Delivery")}</span><div style={{flex: '1', height: '6px', background: '#eef2fa', borderRadius: '99px', overflow: 'hidden'}}><div style={{width: '86%', height: '100%', background: '#1a56db', borderRadius: '99px', animation: 'ucCovB 5s ease-in-out infinite'}}></div></div></div><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{fontSize: '10px', color: '#5b6472', width: '56px', flexShrink: '0'}}>{t("Utilization")}</span><div style={{flex: '1', height: '6px', background: '#eef2fa', borderRadius: '99px', overflow: 'hidden'}}><div style={{width: '71%', height: '100%', background: '#1a56db', borderRadius: '99px', animation: 'ucCovC 5s ease-in-out infinite'}}></div></div></div></div>
                      <div style={{marginTop: '11px', display: 'inline-flex', alignItems: 'center', gap: '6px', background: '#e3f6ec', borderRadius: '7px', padding: '5px 9px', fontSize: '10px', fontWeight: '700', color: '#1a9d55', animation: 'ucToast 5s ease-in-out infinite'}}>{t("＋ Invoice #INV-238 sent")}</div>
                    </div>
                  </div>
                  <div style={{position: 'absolute', insetInlineEnd: '11%', top: '15%', zIndex: '4'}}><div style={{background: 'rgba(255,255,255,.96)', backdropFilter: 'blur(10px)', border: '1px solid #eef1f6', borderRadius: '12px', padding: '10px 14px', boxShadow: '0 18px 40px -18px rgba(15,23,41,.3)', display: 'flex', alignItems: 'center', gap: '9px', whiteSpace: 'nowrap', cursor: 'default', animation: 'floatY 5s ease-in-out infinite', transition: 'transform .25s ease,box-shadow .25s ease'}} data-hv="hv-16"><span style={{width: '9px', height: '9px', borderRadius: '50%', background: '#1a56db', flexShrink: '0', animation: 'pulseDot 2s ease-in-out infinite'}}></span><span style={{fontSize: '12.5px', fontWeight: '700', color: '#0f1729'}}>{t("38.5 hrs logged")}</span></div></div>
                  <div style={{position: 'absolute', insetInlineStart: '11%', bottom: '19%', zIndex: '4'}}><div style={{background: 'rgba(255,255,255,.96)', backdropFilter: 'blur(10px)', border: '1px solid #eef1f6', borderRadius: '12px', padding: '10px 14px', boxShadow: '0 18px 40px -18px rgba(15,23,41,.3)', display: 'flex', alignItems: 'center', gap: '9px', whiteSpace: 'nowrap', cursor: 'default', animation: 'floatY2 5s ease-in-out infinite', transition: 'transform .25s ease,box-shadow .25s ease'}} data-hv="hv-16"><span style={{width: '9px', height: '9px', borderRadius: '50%', background: '#1a9d55', flexShrink: '0', animation: 'pulseDot 2s ease-in-out infinite'}}></span><span style={{fontSize: '12.5px', fontWeight: '700', color: '#0f1729'}}>{t("Invoices Rs 1.2M")}</span></div></div>
                </div>
              </div>
            </div>
          </div>
        </section>
    </>
  );
}
