import { useHome, pressable } from '../HomeContext';
import { useLanguage } from '../../../context/LanguageContext';

export default function ProductsSection() {
  const { c, b, act, state } = useHome();
  const { t } = useLanguage();
  return (
    <>
      <section data-screen-label="Products" className="ag" data-active-pg={['fin', 'pen', 'fie'][state.prodTab]} style={{background: 'linear-gradient(115deg,#eef3fb 0%,#f7faff 46%,#e9f0fd 100%)', borderTop: '1px solid #eef1f6'}}>
          <div style={{maxWidth: '1240px', margin: '0 auto', padding: '100px 32px'}}>
            <div data-reveal="0" style={{opacity: '0', transform: 'translateY(24px)', transition: 'all .7s cubic-bezier(.2,.7,.3,1)', maxWidth: '760px', margin: '0 auto', textAlign: 'center'}}>
              <div style={{display: 'inline-flex', alignItems: 'center', gap: '8px', fontSize: '12.5px', fontWeight: '700', color: '#1a56db', letterSpacing: '1.4px', textTransform: 'uppercase'}}>{t("One platform")}</div>
              <h2 style={{fontSize: '46px', fontWeight: '800', letterSpacing: '-1.8px', margin: '20px 0 0', lineHeight: '1.06', textWrap: 'pretty'}}>{t("Every part of your business.")}<br /><span style={{background: 'linear-gradient(100deg,#1a56db 0%,#4b8bff 100%)', WebkitBackgroundClip: 'text', backgroundClip: 'text', color: 'transparent'}}>{t("One aligned way of working.")}</span></h2>
              <p style={{fontSize: '17px', lineHeight: '1.65', color: '#4b5565', margin: '18px 0 0'}}>{t("One login. One source of truth. Everything your teams do — finance, people, field operations — runs on a single Align platform instead of scattered across disconnected tools. We design, build and support all of it in-house, as one connected way of working.")}</p>
            </div>
      
            <div className="hm-stack" style={{display: 'grid', gridTemplateColumns: '0.8fr 1.2fr', gap: '44px', alignItems: 'center', marginTop: '52px'}}>
              
              <div className="hm-stagger" style={{display: 'flex', flexDirection: 'column', gap: '14px', position: 'relative', zIndex: '20'}}>
      <div data-act="setProd0" {...pressable(() => act('setProd0'))} style={{cursor: 'pointer', background: '#ffffff', border: '1px solid #1a56db', borderRadius: '22px', padding: '24px 26px', transition: 'background .3s ease,border-color .3s ease,box-shadow .3s ease,transform .3s ease', boxShadow: '0 20px 44px -22px rgba(26,86,219,.4)', backdropFilter: 'blur(10px) saturate(1.2)', WebkitBackdropFilter: 'blur(10px) saturate(1.2)'}} data-hv="hv-10">
                <div style={{fontSize: '11.5px', fontWeight: '700', color: '#1a56db', letterSpacing: '1px', textTransform: 'uppercase'}}>{t("Finance & Operations")}</div>
                <div style={{fontSize: '19px', fontWeight: '700', color: '#0f1729', marginTop: '5px'}}>{t("Run the whole operation")}</div>
                <p style={{fontSize: '13.5px', lineHeight: '1.55', color: '#5b6472', margin: '7px 0 0'}}>{t("Finance, inventory, procurement and approvals — the whole operation in one connected flow.")}</p>
              </div>
      <div data-act="setProd1" {...pressable(() => act('setProd1'))} style={{cursor: 'pointer', background: 'rgba(255,255,255,.55)', border: '1px solid #e7ecf5', borderRadius: '22px', padding: '24px 26px', transition: 'background .3s ease,border-color .3s ease,box-shadow .3s ease,transform .3s ease', boxShadow: 'none', backdropFilter: 'blur(10px) saturate(1.2)', WebkitBackdropFilter: 'blur(10px) saturate(1.2)'}} data-hv="hv-10">
                <div style={{fontSize: '11.5px', fontWeight: '700', color: '#1a56db', letterSpacing: '1px', textTransform: 'uppercase'}}>{t("People & Payroll")}</div>
                <div style={{fontSize: '19px', fontWeight: '700', color: '#0f1729', marginTop: '5px'}}>{t("Manage every employee")}</div>
                <p style={{fontSize: '13.5px', lineHeight: '1.55', color: '#5b6472', margin: '7px 0 0'}}>{t("Attendance, leave, payroll and people analytics — one place for managers and every employee.")}</p>
              </div>
      <div data-act="setProd2" {...pressable(() => act('setProd2'))} style={{cursor: 'pointer', background: 'rgba(255,255,255,.55)', border: '1px solid #e7ecf5', borderRadius: '22px', padding: '24px 26px', transition: 'background .3s ease,border-color .3s ease,box-shadow .3s ease,transform .3s ease', boxShadow: 'none', backdropFilter: 'blur(10px) saturate(1.2)', WebkitBackdropFilter: 'blur(10px) saturate(1.2)'}} data-hv="hv-10">
                <div style={{fontSize: '11.5px', fontWeight: '700', color: '#1a56db', letterSpacing: '1px', textTransform: 'uppercase'}}>{t("Field & Sales")}</div>
                <div style={{fontSize: '19px', fontWeight: '700', color: '#0f1729', marginTop: '5px'}}>{t("See the field in real time")}</div>
                <p style={{fontSize: '13.5px', lineHeight: '1.55', color: '#5b6472', margin: '7px 0 0'}}>{t("Field visits, samples, routes and live KPIs — full visibility over teams on the ground.")}</p>
              </div>
              </div>
      
              
              <div data-reveal="1" className="hm-scale-wrap" aria-hidden="true" style={{opacity: '0', transform: 'translateY(24px)', transition: 'all .7s cubic-bezier(.2,.7,.3,1)', '--hm-w': '680px', '--hm-h': '560px'}}>
                <div className="hm-scale-panel" style={{position: 'relative', height: '560px'}}>
                <div style={{position: 'absolute', top: '-30px', insetInlineEnd: '-30px', width: '320px', height: '320px', borderRadius: '50%', background: 'radial-gradient(circle,rgba(26,86,219,.15) 0%,rgba(26,86,219,0) 68%)', pointerEvents: 'none', zIndex: '0'}}></div>
                <div style={{position: 'absolute', bottom: '-30px', insetInlineStart: '-10px', width: '280px', height: '280px', borderRadius: '50%', background: 'radial-gradient(circle,rgba(75,139,255,.13) 0%,rgba(75,139,255,0) 68%)', pointerEvents: 'none', zIndex: '0'}}></div>
                <div data-pg="fin" style={{display: 'block', position: 'absolute', top: '6px', insetInlineEnd: '3%', zIndex: '5', width: '263px', background: '#fff', border: '1px solid #e7ecf5', borderRadius: '18px', boxShadow: '0 30px 60px -28px rgba(26,86,219,.4)', padding: '17px 18px', animation: 'dashDrift1 20s ease-in-out 0.0s infinite'}}><div style={{display: 'flex', alignItems: 'center', gap: '9px'}}><span style={{width: '33px', height: '26px', borderRadius: '8px', background: 'linear-gradient(135deg,#1a56db,#4b8bff)', display: 'grid', placeItems: 'center', color: '#fff', fontWeight: '800', fontSize: '15px', flexShrink: '0'}}>A</span><span style={{fontSize: '15.6px', fontWeight: '700', color: '#0f1729'}}>{t("Finance & Ops")}</span></div><div style={{fontSize: '11.9px', color: '#657085', textTransform: 'uppercase', letterSpacing: '.5px', marginTop: '13px'}}>{t("Total Sales")}</div><div style={{fontSize: '27.5px', fontWeight: '800', color: '#0f1729', marginTop: '3px'}}>1,490,010</div><div style={{fontSize: '12.5px', fontWeight: '700', color: '#157d44', marginTop: '2px'}}>&uarr; 12.4%</div></div>
                <div data-pg="fin" style={{display: 'block', position: 'absolute', top: '214px', insetInlineStart: '0', zIndex: '6', width: '263px', background: '#fff', border: '1px solid #e7ecf5', borderRadius: '18px', boxShadow: '0 30px 60px -28px rgba(26,86,219,.4)', padding: '17px 18px', animation: 'dashDrift2 23s ease-in-out 1.5s infinite'}}><div style={{display: 'flex', alignItems: 'center', gap: '9px'}}><span style={{width: '33px', height: '26px', borderRadius: '8px', background: 'linear-gradient(135deg,#1a56db,#4b8bff)', display: 'grid', placeItems: 'center', color: '#fff', fontWeight: '800', fontSize: '15px', flexShrink: '0'}}>A</span><span style={{fontSize: '15.6px', fontWeight: '700', color: '#0f1729'}}>{t("Finance & Ops")}</span></div><div style={{fontSize: '11.9px', color: '#657085', textTransform: 'uppercase', letterSpacing: '.5px', marginTop: '13px'}}>{t("Invoices")}</div><div style={{fontSize: '27.5px', fontWeight: '800', color: '#0f1729', marginTop: '3px'}}>1,138</div><div style={{fontSize: '12.5px', fontWeight: '700', color: '#157d44', marginTop: '2px'}}>&uarr; 5.1%</div></div>
                <div data-pg="fin" style={{display: 'block', position: 'absolute', top: '406px', insetInlineEnd: '9%', zIndex: '5', width: '263px', background: '#fff', border: '1px solid #e7ecf5', borderRadius: '18px', boxShadow: '0 30px 60px -28px rgba(26,86,219,.4)', padding: '17px 18px', animation: 'dashDrift3 26s ease-in-out 3.0s infinite'}}><div style={{display: 'flex', alignItems: 'center', gap: '9px'}}><span style={{width: '33px', height: '26px', borderRadius: '8px', background: 'linear-gradient(135deg,#1a56db,#4b8bff)', display: 'grid', placeItems: 'center', color: '#fff', fontWeight: '800', fontSize: '15px', flexShrink: '0'}}>A</span><span style={{fontSize: '15.6px', fontWeight: '700', color: '#0f1729'}}>{t("Finance & Ops")}</span></div><div style={{fontSize: '11.9px', color: '#657085', textTransform: 'uppercase', letterSpacing: '.5px', marginTop: '13px'}}>{t("Profit")}</div><div style={{fontSize: '27.5px', fontWeight: '800', color: '#0f1729', marginTop: '3px'}}>910,063</div><div style={{fontSize: '12.5px', fontWeight: '700', color: '#157d44', marginTop: '2px'}}>&uarr; 18.9%</div></div>
                <div data-pg="pen" style={{display: 'none', position: 'absolute', top: '6px', insetInlineEnd: '3%', zIndex: '5', width: '263px', background: '#fff', border: '1px solid #e7ecf5', borderRadius: '18px', boxShadow: '0 30px 60px -28px rgba(26,86,219,.4)', padding: '17px 18px', animation: 'dashDrift4 29s ease-in-out 4.5s infinite'}}><div style={{display: 'flex', alignItems: 'center', gap: '9px'}}><span style={{width: '33px', height: '26px', borderRadius: '8px', background: '#e8effc', display: 'grid', placeItems: 'center', color: '#1a56db', fontWeight: '800', fontSize: '15px', flexShrink: '0'}}>P</span><span style={{fontSize: '15.6px', fontWeight: '700', color: '#0f1729'}}>{t("People & Payroll")}</span></div><div style={{display: 'flex', alignItems: 'center', gap: '11px', marginTop: '13px'}}><div style={{width: '63px', height: '50px', borderRadius: '50%', background: 'conic-gradient(#1a9d55 0 92%,#eef2f8 92% 100%)', display: 'grid', placeItems: 'center', flexShrink: '0'}}><div style={{width: '45px', height: '36px', borderRadius: '50%', background: '#fff', display: 'grid', placeItems: 'center', fontSize: '13.8px', fontWeight: '800', color: '#0f1729'}}>92%</div></div><div><div style={{fontSize: '11.9px', color: '#657085', textTransform: 'uppercase', letterSpacing: '.5px'}}>{t("Attendance")}</div><div style={{fontSize: '20px', fontWeight: '800', color: '#0f1729'}}>228/248</div></div></div></div>
                <div data-pg="pen" style={{display: 'none', position: 'absolute', top: '214px', insetInlineStart: '0', zIndex: '6', width: '263px', background: '#fff', border: '1px solid #e7ecf5', borderRadius: '18px', boxShadow: '0 30px 60px -28px rgba(26,86,219,.4)', padding: '17px 18px', animation: 'dashDrift1 32s ease-in-out 6.0s infinite'}}><div style={{display: 'flex', alignItems: 'center', gap: '9px'}}><span style={{width: '33px', height: '26px', borderRadius: '8px', background: '#e8effc', display: 'grid', placeItems: 'center', color: '#1a56db', fontWeight: '800', fontSize: '15px', flexShrink: '0'}}>P</span><span style={{fontSize: '15.6px', fontWeight: '700', color: '#0f1729'}}>{t("People & Payroll")}</span></div><div style={{fontSize: '11.9px', color: '#657085', textTransform: 'uppercase', letterSpacing: '.5px', marginTop: '13px'}}>{t("On Leave")}</div><div style={{fontSize: '27.5px', fontWeight: '800', color: '#0f1729', marginTop: '3px'}}>12</div><div style={{fontSize: '12.5px', fontWeight: '700', color: '#657085', marginTop: '2px'}}> </div></div>
                <div data-pg="pen" style={{display: 'none', position: 'absolute', top: '406px', insetInlineEnd: '9%', zIndex: '5', width: '263px', background: '#fff', border: '1px solid #e7ecf5', borderRadius: '18px', boxShadow: '0 30px 60px -28px rgba(26,86,219,.4)', padding: '17px 18px', animation: 'dashDrift2 20s ease-in-out 7.5s infinite'}}><div style={{display: 'flex', alignItems: 'center', gap: '9px'}}><span style={{width: '33px', height: '26px', borderRadius: '8px', background: '#e8effc', display: 'grid', placeItems: 'center', color: '#1a56db', fontWeight: '800', fontSize: '15px', flexShrink: '0'}}>P</span><span style={{fontSize: '15.6px', fontWeight: '700', color: '#0f1729'}}>{t("People & Payroll")}</span></div><div style={{fontSize: '11.9px', color: '#657085', textTransform: 'uppercase', letterSpacing: '.5px', marginTop: '13px'}}>{t("Payroll")}</div><div style={{fontSize: '27.5px', fontWeight: '800', color: '#0f1729', marginTop: '3px'}}>{t("Run ✓")}</div><div style={{fontSize: '12.5px', fontWeight: '700', color: '#157d44', marginTop: '2px'}}> </div></div>
                <div data-pg="fie" style={{display: 'none', position: 'absolute', top: '6px', insetInlineEnd: '3%', zIndex: '5', width: '263px', background: '#fff', border: '1px solid #e7ecf5', borderRadius: '18px', boxShadow: '0 30px 60px -28px rgba(26,86,219,.4)', padding: '17px 18px', animation: 'dashDrift3 23s ease-in-out 9.0s infinite'}}><div style={{display: 'flex', alignItems: 'center', gap: '9px'}}><span style={{width: '33px', height: '26px', borderRadius: '8px', background: '#e8effc', display: 'grid', placeItems: 'center', color: '#1a56db', fontWeight: '800', fontSize: '15px', flexShrink: '0'}}>F</span><span style={{fontSize: '15.6px', fontWeight: '700', color: '#0f1729'}}>{t("Field & Sales")}</span></div><div style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: '13px'}}><span style={{fontSize: '15px', color: '#39404d'}}>{t("Reps on visit")}</span><span style={{fontSize: '21.3px', fontWeight: '800', color: '#0f1729'}}>18</span></div><div style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: '7px'}}><span style={{fontSize: '15px', color: '#39404d'}}>{t("Routes")}</span><span style={{fontSize: '21.3px', fontWeight: '800', color: '#0f1729'}}>7</span></div></div>
                <div data-pg="fie" style={{display: 'none', position: 'absolute', top: '214px', insetInlineStart: '0', zIndex: '6', width: '263px', background: '#fff', border: '1px solid #e7ecf5', borderRadius: '18px', boxShadow: '0 30px 60px -28px rgba(26,86,219,.4)', padding: '17px 18px', animation: 'dashDrift4 26s ease-in-out 10.5s infinite'}}><div style={{display: 'flex', alignItems: 'center', gap: '9px'}}><span style={{width: '33px', height: '26px', borderRadius: '8px', background: '#e8effc', display: 'grid', placeItems: 'center', color: '#1a56db', fontWeight: '800', fontSize: '15px', flexShrink: '0'}}>F</span><span style={{fontSize: '15.6px', fontWeight: '700', color: '#0f1729'}}>{t("Field & Sales")}</span></div><div style={{fontSize: '11.9px', color: '#657085', textTransform: 'uppercase', letterSpacing: '.5px', marginTop: '13px'}}>{t("Coverage")}</div><div style={{fontSize: '27.5px', fontWeight: '800', color: '#0f1729', marginTop: '3px'}}>87%</div><div style={{fontSize: '12.5px', fontWeight: '700', color: '#157d44', marginTop: '2px'}}>&uarr; 6%</div></div>
                <div data-pg="fie" style={{display: 'none', position: 'absolute', top: '406px', insetInlineEnd: '9%', zIndex: '5', width: '263px', background: '#fff', border: '1px solid #e7ecf5', borderRadius: '18px', boxShadow: '0 30px 60px -28px rgba(26,86,219,.4)', padding: '17px 18px', animation: 'dashDrift1 29s ease-in-out 12.0s infinite'}}><div style={{display: 'flex', alignItems: 'center', gap: '9px'}}><span style={{width: '33px', height: '26px', borderRadius: '8px', background: '#e8effc', display: 'grid', placeItems: 'center', color: '#1a56db', fontWeight: '800', fontSize: '15px', flexShrink: '0'}}>F</span><span style={{fontSize: '15.6px', fontWeight: '700', color: '#0f1729'}}>{t("Field & Sales")}</span></div><div style={{fontSize: '11.9px', color: '#657085', textTransform: 'uppercase', letterSpacing: '.5px', marginTop: '13px'}}>{t("Live now")}</div><div style={{fontSize: '27.5px', fontWeight: '800', color: '#0f1729', marginTop: '3px'}}>{t("On track")}</div><div style={{fontSize: '12.5px', fontWeight: '700', color: '#157d44', marginTop: '2px'}}> </div></div>
              
                <div data-pg="fin" style={{display: 'block', position: 'absolute', top: '150px', insetInlineStart: '46%', transform: 'translateX(-50%)', zIndex: '7', width: '220px', background: '#fff', border: '1px solid #e7ecf5', borderRadius: '16px', boxShadow: '0 26px 54px -26px rgba(15,23,41,.36)', padding: '15px 16px', animation: 'dashDriftC 24s ease-in-out .3s infinite'}}><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{width: '30px', height: '24px', borderRadius: '7px', background: 'linear-gradient(135deg,#1a56db,#4b8bff)', display: 'grid', placeItems: 'center', color: '#fff', fontWeight: '800', fontSize: '13.8px', flexShrink: '0'}}>A</span><span style={{fontSize: '14.4px', fontWeight: '700', color: '#0f1729'}}>{t("Finance & Ops")}</span></div><div style={{fontSize: '11.3px', color: '#657085', textTransform: 'uppercase', letterSpacing: '.5px', marginTop: '11px'}}>{t("Expenses")}</div><div style={{fontSize: '23.8px', fontWeight: '800', color: '#0f1729', marginTop: '2px'}}>279,946</div><div style={{fontSize: '11.9px', fontWeight: '700', color: '#d0473e', marginTop: '2px'}}>&darr; 2.3%</div></div>
                <div data-pg="pen" style={{display: 'none', position: 'absolute', top: '150px', insetInlineStart: '46%', transform: 'translateX(-50%)', zIndex: '7', width: '220px', background: '#fff', border: '1px solid #e7ecf5', borderRadius: '16px', boxShadow: '0 26px 54px -26px rgba(15,23,41,.36)', padding: '15px 16px', animation: 'dashDriftC 24s ease-in-out .3s infinite'}}><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{width: '30px', height: '24px', borderRadius: '7px', background: '#e8effc', display: 'grid', placeItems: 'center', color: '#1a56db', fontWeight: '800', fontSize: '13.8px', flexShrink: '0'}}>P</span><span style={{fontSize: '14.4px', fontWeight: '700', color: '#0f1729'}}>{t("People & Payroll")}</span></div><div style={{fontSize: '11.3px', color: '#657085', textTransform: 'uppercase', letterSpacing: '.5px', marginTop: '11px'}}>{t("Headcount")}</div><div style={{fontSize: '23.8px', fontWeight: '800', color: '#0f1729', marginTop: '2px'}}>248</div><div style={{fontSize: '11.9px', fontWeight: '700', color: '#157d44', marginTop: '2px'}}>{t("↑ 4 new")}</div></div>
                <div data-pg="fie" style={{display: 'none', position: 'absolute', top: '150px', insetInlineStart: '46%', transform: 'translateX(-50%)', zIndex: '7', width: '220px', background: '#fff', border: '1px solid #e7ecf5', borderRadius: '16px', boxShadow: '0 26px 54px -26px rgba(15,23,41,.36)', padding: '15px 16px', animation: 'dashDriftC 24s ease-in-out .3s infinite'}}><div style={{display: 'flex', alignItems: 'center', gap: '8px'}}><span style={{width: '30px', height: '24px', borderRadius: '7px', background: '#e8effc', display: 'grid', placeItems: 'center', color: '#1a56db', fontWeight: '800', fontSize: '13.8px', flexShrink: '0'}}>F</span><span style={{fontSize: '14.4px', fontWeight: '700', color: '#0f1729'}}>{t("Field & Sales")}</span></div><div style={{fontSize: '11.3px', color: '#657085', textTransform: 'uppercase', letterSpacing: '.5px', marginTop: '11px'}}>{t("Deals closed")}</div><div style={{fontSize: '23.8px', fontWeight: '800', color: '#0f1729', marginTop: '2px'}}>9</div><div style={{fontSize: '11.9px', fontWeight: '700', color: '#657085', marginTop: '2px'}}>{t("this week")}</div></div>
                </div>
              </div>
            </div>
          </div>
        </section>
    </>
  );
}
