'use no memo'; // Compiler skipped this markup before the split; memoizing its ~300 inline styles adds ~20 KB per mockup.
import { useLanguage } from '../../../../context/LanguageContext';

/* Field Force hero mockup. Rendered by HeroSection while Field Force is the
   active product. */
export default function FieldForceMockup({ scrollRegion }) {
  const { t } = useLanguage();
  return (
    <>
            <div className="hm-float-wrap" style={{position: 'relative', animation: 'slideInR .55s cubic-bezier(.2,.7,.3,1) both'}}>
              <div className="hm-scale-scroll-wrap hm-float-main" {...scrollRegion} style={{'--hm-w': '1040px', '--hm-h': '520px'}}>
              <div className="hm-scale-scroll" style={{display: 'flex', background: '#ffffff', border: '1px solid #e7ecf5', borderRadius: '16px', boxShadow: '0 50px 100px -40px rgba(15,23,41,.35)', overflow: 'hidden', minHeight: '520px'}}>
                
                <div style={{width: '180px', flexShrink: '0', borderInlineEnd: '1px solid #f0f3f8', display: 'flex', flexDirection: 'column', padding: '16px 12px'}}>
                  <div style={{display: 'flex', alignItems: 'center', gap: '7px', padding: '0 6px 14px'}}><span style={{fontSize: '17px', fontWeight: '800', letterSpacing: '1px', color: '#0e9384'}}>F<span style={{color: '#f5a623'}}>O</span>RCE</span></div>
                  <div style={{display: 'flex', alignItems: 'center', gap: '9px', background: '#e6f5f2', color: '#0e9384', borderRadius: '10px', padding: '9px 11px', fontSize: '12px', fontWeight: '700'}}><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#0e9384" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M3 17l6-6 4 4 8-8"></path></svg>{t("Reports")}</div>
                  <div style={{display: 'flex', alignItems: 'center', gap: '9px', color: '#5b6472', borderRadius: '10px', padding: '9px 11px', fontSize: '12px', fontWeight: '500', marginTop: '2px'}}><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#5b6472" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><line x1="8" y1="6" x2="21" y2="6"></line><line x1="8" y1="12" x2="21" y2="12"></line><line x1="8" y1="18" x2="21" y2="18"></line><line x1="3" y1="6" x2="3.01" y2="6"></line><line x1="3" y1="12" x2="3.01" y2="12"></line><line x1="3" y1="18" x2="3.01" y2="18"></line></svg>{t("Call List")}</div>
                  <div style={{display: 'flex', alignItems: 'center', gap: '9px', color: '#5b6472', borderRadius: '10px', padding: '9px 11px', fontSize: '12px', fontWeight: '500', marginTop: '2px'}}><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#5b6472" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 9-3 9h18s-3-2-3-9"></path><path d="M13.7 21a2 2 0 0 1-3.4 0"></path></svg>{t("Alerts")}</div>
                  <div style={{marginTop: 'auto'}}>
                    <div style={{display: 'flex', alignItems: 'center', gap: '8px', border: '1px solid #e0e6f0', borderRadius: '10px', padding: '8px 10px', fontSize: '11px', color: '#39404d'}}><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#0e9384" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="8" r="4"></circle><path d="M4 21a8 8 0 0 1 16 0"></path></svg>Ijaz Bhatti <span style={{marginInlineStart: 'auto', color: '#657085'}}>⇅</span></div>
                    <div style={{display: 'flex', alignItems: 'center', gap: '8px', padding: '10px 6px 0', fontSize: '11px', color: '#39404d'}}><span style={{width: '26px', height: '26px', borderRadius: '50%', background: '#0e9384', color: '#fff', display: 'grid', placeItems: 'center', fontSize: '9px', fontWeight: '700'}}>AD</span><span><b style={{color: '#0f1729'}}>{t("Admin")}</b><span style={{display: 'block', fontSize: '9px', color: '#657085'}}>{t("Sign out")}</span></span></div>
                  </div>
                </div>
                
                <div style={{flex: '1', minWidth: '0', display: 'flex', flexDirection: 'column'}}>
                  <div style={{display: 'flex', alignItems: 'center', padding: '15px 20px', borderBottom: '1px solid #f0f3f8'}}><span style={{fontSize: '17px', fontWeight: '800', color: '#0f1729'}}>{t("Reports")}</span><span style={{marginInlineStart: 'auto', display: 'flex', gap: '8px'}}><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#5b6472" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"></path><path d="M7 10l5 5 5-5"></path><line x1="12" y1="15" x2="12" y2="3"></line></svg><svg width="15" height="15" viewBox="0 0 24 24" fill="none" stroke="#5b6472" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 9-3 9h18s-3-2-3-9"></path></svg></span></div>
                  <div style={{padding: '14px 20px', background: '#f7f9fb', flex: '1'}}>
                    <div style={{display: 'flex', gap: '8px', flexWrap: 'wrap'}}>
                      <span style={{fontSize: '10.5px', fontWeight: '600', color: '#39404d', background: '#fff', border: '1px solid #e6e9ef', borderRadius: '99px', padding: '6px 13px'}}>{t("Compliance & Execution")}</span><span style={{fontSize: '10.5px', fontWeight: '600', color: '#39404d', background: '#fff', border: '1px solid #e6e9ef', borderRadius: '99px', padding: '6px 13px'}}>{t("Coverage Reports")}</span><span style={{fontSize: '10.5px', fontWeight: '600', color: '#39404d', background: '#fff', border: '1px solid #e6e9ef', borderRadius: '99px', padding: '6px 13px'}}>{t("Depth Reports")}</span><span style={{fontSize: '10.5px', fontWeight: '600', color: '#39404d', background: '#fff', border: '1px solid #e6e9ef', borderRadius: '99px', padding: '6px 13px'}}>{t("Quality Reports")}</span>
                      <span style={{fontSize: '10.5px', fontWeight: '700', color: '#7a4fd6', background: '#f0eafd', border: '1px solid #ddd0f7', borderRadius: '99px', padding: '6px 13px'}}>{t("✓ Pan Pakistan View")}</span>
                      <span style={{fontSize: '10.5px', fontWeight: '600', color: '#39404d', background: '#fff', border: '1px solid #e6e9ef', borderRadius: '99px', padding: '6px 13px'}}>{t("Team Monthly Plan")}</span>
                    </div>
                    <div style={{display: 'flex', alignItems: 'center', gap: '8px', marginTop: '12px'}}>
                      <span style={{fontSize: '11px', fontWeight: '600', color: '#926702', background: '#fdf6e3', borderRadius: '99px', padding: '6px 15px'}}>{t("Yearly")}</span>
                      <span style={{fontSize: '11px', fontWeight: '600', color: '#926702', background: '#fdf6e3', borderRadius: '99px', padding: '6px 15px'}}>{t("Quarterly")}</span>
                      <span style={{fontSize: '11px', fontWeight: '700', color: '#fff', background: '#0e9384', borderRadius: '99px', padding: '6px 17px'}}>{t("Monthly")}</span>
                      <span style={{marginInlineStart: 'auto', display: 'flex', alignItems: 'center', gap: '10px', fontSize: '12px', fontWeight: '700', color: '#0f1729'}}><span style={{color: '#657085'}}>‹</span>{t("July 2026")}<span style={{color: '#657085'}}>›</span></span>
                    </div>
                    <div style={{background: '#fff', border: '1px solid #eef1f6', borderRadius: '13px', padding: '14px 16px', marginTop: '12px'}}>
                      <div style={{display: 'flex', alignItems: 'center', gap: '7px', fontSize: '12.5px', fontWeight: '700', color: '#0f1729'}}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#0e9384" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3"></polygon></svg>{t("Pan Pakistan Filters")}</div>
                      <div style={{display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '12px', marginTop: '11px'}}>
                        <span><span style={{display: 'block', fontSize: '9.5px', color: '#657085'}}>{t("Region")}</span><span style={{display: 'flex', alignItems: 'center', fontSize: '11.5px', color: '#39404d', background: '#f4f6fa', borderRadius: '9px', padding: '8px 11px', marginTop: '4px'}}>{t("All Regions")}<span style={{marginInlineStart: 'auto', color: '#657085'}}>▾</span></span></span><span><span style={{display: 'block', fontSize: '9.5px', color: '#657085'}}>{t("Zone")}</span><span style={{display: 'flex', alignItems: 'center', fontSize: '11.5px', color: '#39404d', background: '#f4f6fa', borderRadius: '9px', padding: '8px 11px', marginTop: '4px'}}>{t("All Zones")}<span style={{marginInlineStart: 'auto', color: '#657085'}}>▾</span></span></span><span><span style={{display: 'block', fontSize: '9.5px', color: '#657085'}}>{t("FM Name")}</span><span style={{display: 'flex', alignItems: 'center', fontSize: '11.5px', color: '#39404d', background: '#f4f6fa', borderRadius: '9px', padding: '8px 11px', marginTop: '4px'}}>{t("All FMs")}<span style={{marginInlineStart: 'auto', color: '#657085'}}>▾</span></span></span>
                      </div>
                    </div>
                    <div style={{background: '#fff', border: '1px solid #eef1f6', borderRadius: '13px', marginTop: '12px', overflow: 'hidden'}}>
                      <div style={{display: 'flex', alignItems: 'center', gap: '7px', fontSize: '12.5px', fontWeight: '700', color: '#0f1729', padding: '13px 16px 4px'}}><svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#0e9384" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"></circle><path d="M2 12h20M12 2a15 15 0 0 1 0 20a15 15 0 0 1 0-20"></path></svg>{t("Pan Pakistan Performance Dashboard")}</div>
                      <div style={{display: 'grid', gridTemplateColumns: '1.5fr .8fr .9fr .9fr 1fr .95fr .85fr .8fr .85fr', padding: '9px 16px', fontSize: '8.5px', fontWeight: '700', letterSpacing: '.5px', color: '#657085'}}><span style={{}}>{t("FIELD MANAGER")}</span><span style={{textAlign: 'center'}}>{t("TOTAL DOCTORS")}</span><span style={{textAlign: 'center'}}>{t("TOTAL INSTITUTES")}</span><span style={{textAlign: 'center'}}>{t("PLANNED CALLS")}</span><span style={{textAlign: 'center'}}>{t("UNPLANNED CALLS")}</span><span style={{textAlign: 'center'}}>{t("COMPLETED CALLS")}</span><span style={{textAlign: 'center'}}>{t("DEFERRED")}</span><span style={{textAlign: 'center'}}>{t("TOTAL CALLS")}</span><span style={{textAlign: 'center'}}>{t("COMPLIANCE %")}</span></div>
                      <div style={{display: 'grid', gridTemplateColumns: '1.5fr .8fr .9fr .9fr 1fr .95fr .85fr .8fr .85fr', alignItems: 'center', padding: '11px 16px', borderTop: '1px solid #f0f3f8', fontSize: '11.5px', color: '#39404d'}}>
        <span style={{display: 'flex', alignItems: 'center', gap: '9px'}}><span style={{width: '26px', height: '26px', borderRadius: '50%', background: '#e6f5f2', color: '#0e9384', display: 'grid', placeItems: 'center', fontSize: '9px', fontWeight: '700'}}>SF</span><b style={{color: '#0f1729'}}>{t("Sattar Farooqi")}</b></span>
        <span style={{textAlign: 'center'}}>60</span><span style={{textAlign: 'center'}}>15</span><span style={{textAlign: 'center'}}>71</span><span style={{textAlign: 'center'}}>3</span><span style={{textAlign: 'center'}}>31</span><span style={{textAlign: 'center'}}>2</span><span style={{textAlign: 'center', fontWeight: '700', color: '#0f1729'}}>74</span>
        <span style={{textAlign: 'center'}}><span style={{fontSize: '10.5px', fontWeight: '700', color: '#fdf3d7', background: '41%', borderRadius: '99px', padding: '3px 10px'}}>74</span></span>
      </div><div style={{display: 'grid', gridTemplateColumns: '1.5fr .8fr .9fr .9fr 1fr .95fr .85fr .8fr .85fr', alignItems: 'center', padding: '11px 16px', borderTop: '1px solid #f0f3f8', fontSize: '11.5px', color: '#39404d'}}>
        <span style={{display: 'flex', alignItems: 'center', gap: '9px'}}><span style={{width: '26px', height: '26px', borderRadius: '50%', background: '#e8effc', color: '#1a56db', display: 'grid', placeItems: 'center', fontSize: '9px', fontWeight: '700'}}>NA</span><b style={{color: '#0f1729'}}>{t("Naveed Akram")}</b></span>
        <span style={{textAlign: 'center'}}>66</span><span style={{textAlign: 'center'}}>18</span><span style={{textAlign: 'center'}}>92</span><span style={{textAlign: 'center'}}>5</span><span style={{textAlign: 'center'}}>58</span><span style={{textAlign: 'center'}}>1</span><span style={{textAlign: 'center', fontWeight: '700', color: '#0f1729'}}>97</span>
        <span style={{textAlign: 'center'}}><span style={{fontSize: '10.5px', fontWeight: '700', color: '#e6f5ec', background: '63%', borderRadius: '99px', padding: '3px 10px'}}>97</span></span>
      </div><div style={{display: 'grid', gridTemplateColumns: '1.5fr .8fr .9fr .9fr 1fr .95fr .85fr .8fr .85fr', alignItems: 'center', padding: '11px 16px', borderTop: '1px solid #f0f3f8', fontSize: '11.5px', color: '#39404d'}}>
        <span style={{display: 'flex', alignItems: 'center', gap: '9px'}}><span style={{width: '26px', height: '26px', borderRadius: '50%', background: '#f0eafd', color: '#7a4fd6', display: 'grid', placeItems: 'center', fontSize: '9px', fontWeight: '700'}}>{t("HR")}</span><b style={{color: '#0f1729'}}>{t("Hamza Raza")}</b></span>
        <span style={{textAlign: 'center'}}>59</span><span style={{textAlign: 'center'}}>16</span><span style={{textAlign: 'center'}}>44</span><span style={{textAlign: 'center'}}>2</span><span style={{textAlign: 'center'}}>29</span><span style={{textAlign: 'center'}}>3</span><span style={{textAlign: 'center', fontWeight: '700', color: '#0f1729'}}>46</span>
        <span style={{textAlign: 'center'}}><span style={{fontSize: '10.5px', fontWeight: '700', color: '#fdf3d7', background: '47%', borderRadius: '99px', padding: '3px 10px'}}>46</span></span>
      </div><div style={{display: 'grid', gridTemplateColumns: '1.5fr .8fr .9fr .9fr 1fr .95fr .85fr .8fr .85fr', alignItems: 'center', padding: '11px 16px', borderTop: '1px solid #f0f3f8', fontSize: '11.5px', color: '#39404d'}}>
        <span style={{display: 'flex', alignItems: 'center', gap: '9px'}}><span style={{width: '26px', height: '26px', borderRadius: '50%', background: '#fdeef2', color: '#ce2963', display: 'grid', placeItems: 'center', fontSize: '9px', fontWeight: '700'}}>ZM</span><b style={{color: '#0f1729'}}>{t("Zohaib Malik")}</b></span>
        <span style={{textAlign: 'center'}}>55</span><span style={{textAlign: 'center'}}>14</span><span style={{textAlign: 'center'}}>70</span><span style={{textAlign: 'center'}}>3</span><span style={{textAlign: 'center'}}>50</span><span style={{textAlign: 'center'}}>1</span><span style={{textAlign: 'center', fontWeight: '700', color: '#0f1729'}}>73</span>
        <span style={{textAlign: 'center'}}><span style={{fontSize: '10.5px', fontWeight: '700', color: '#e6f5ec', background: '68%', borderRadius: '99px', padding: '3px 10px'}}>73</span></span>
      </div><div style={{display: 'grid', gridTemplateColumns: '1.5fr .8fr .9fr .9fr 1fr .95fr .85fr .8fr .85fr', alignItems: 'center', padding: '11px 16px', borderTop: '1px solid #f0f3f8', fontSize: '11.5px', color: '#39404d'}}>
        <span style={{display: 'flex', alignItems: 'center', gap: '9px'}}><span style={{width: '26px', height: '26px', borderRadius: '50%', background: '#e6f5f2', color: '#0e9384', display: 'grid', placeItems: 'center', fontSize: '9px', fontWeight: '700'}}>TK</span><b style={{color: '#0f1729'}}>{t("Taimur Kazmi")}</b></span>
        <span style={{textAlign: 'center'}}>63</span><span style={{textAlign: 'center'}}>17</span><span style={{textAlign: 'center'}}>81</span><span style={{textAlign: 'center'}}>4</span><span style={{textAlign: 'center'}}>52</span><span style={{textAlign: 'center'}}>2</span><span style={{textAlign: 'center', fontWeight: '700', color: '#0f1729'}}>85</span>
        <span style={{textAlign: 'center'}}><span style={{fontSize: '10.5px', fontWeight: '700', color: '#e6f5ec', background: '61%', borderRadius: '99px', padding: '3px 10px'}}>85</span></span>
      </div>
                    </div>
                  </div>
                </div>
              </div>
              </div>
              <span className="hm-float-caption">{t("📋 Every call, logged")}</span>
              <div className="hm-float" style={{position: 'absolute', bottom: '-30px', insetInlineStart: '-26px', zIndex: '8', width: '262px', background: '#fff', border: '1px solid #eef1f6', borderRadius: '18px', boxShadow: '0 40px 78px -24px rgba(15,23,41,.42)', padding: '18px 19px', animation: 'floatY 7s ease-in-out infinite'}}>
                <div style={{display: 'flex', alignItems: 'center'}}><span style={{fontSize: '16px', fontWeight: '800', color: '#0f1729'}}>{t("Call Details")}</span><span style={{marginInlineStart: 'auto', width: '22px', height: '22px', borderRadius: '50%', background: '#f3f5fb', display: 'grid', placeItems: 'center', fontSize: '10px', color: '#5b6472'}}>✕</span></div>
                <div style={{fontSize: '9px', fontWeight: '700', letterSpacing: '1px', color: '#657085', marginTop: '13px'}}>{t("DOCTOR INFORMATION")}</div>
                <div style={{display: 'flex', alignItems: 'center', gap: '10px', background: '#f4f8f7', border: '1px solid #e2f0ed', borderRadius: '12px', padding: '10px 11px', marginTop: '5px'}}><span style={{width: '34px', height: '34px', borderRadius: '50%', background: '#0e9384', color: '#fff', display: 'grid', placeItems: 'center', fontSize: '12px', fontWeight: '700', flexShrink: '0'}}>FR</span><span><span style={{display: 'block', fontSize: '12.5px', fontWeight: '700', color: '#0f1729'}}>{t("Dr. Faizan Rehman")}</span><span style={{display: 'block', fontSize: '9.5px', color: '#657085', lineHeight: '1.4'}}>{t("Northline General Hospital, Lahore")}</span></span></div>
                <div style={{fontSize: '9px', fontWeight: '700', letterSpacing: '1px', color: '#657085', marginTop: '13px'}}>{t("CALL INFORMATION")}</div>
                <div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '8px', marginTop: '5px'}}>
                  <span style={{border: '1px solid #eef1f6', borderRadius: '11px', padding: '9px 11px'}}><span style={{display: 'block', fontSize: '9px', color: '#657085'}}>{t("🗓 Date")}</span><span style={{display: 'block', fontSize: '12px', fontWeight: '700', color: '#0f1729', marginTop: '2px'}}>7/14/2026</span></span>
                  <span style={{border: '1px solid #eef1f6', borderRadius: '11px', padding: '9px 11px'}}><span style={{display: 'block', fontSize: '9px', color: '#657085'}}>{t("◷ Time")}</span><span style={{display: 'block', fontSize: '12px', fontWeight: '700', color: '#0f1729', marginTop: '2px'}}>03:30 PM</span></span>
                  <span style={{border: '1px solid #eef1f6', borderRadius: '11px', padding: '9px 11px'}}><span style={{display: 'block', fontSize: '9px', color: '#657085'}}>{t("Call Type")}</span><span style={{display: 'block', fontSize: '12px', fontWeight: '700', color: '#0f1729', marginTop: '2px'}}>{t("Tele-Visit")}</span></span>
                  <span style={{border: '1px solid #eef1f6', borderRadius: '11px', padding: '9px 11px', display: 'flex', alignItems: 'center'}}><span style={{fontSize: '10.5px', fontWeight: '700', color: '#157d44', background: '#e6f5ec', borderRadius: '99px', padding: '3px 11px'}}>{t("✓ Completed")}</span></span>
                </div>
              </div>
      
              
              <span className="hm-float-caption">{t("📱 Field visits, on mobile")}</span>
              <div className="hm-float" style={{position: 'absolute', top: '-28px', insetInlineEnd: '-20px', zIndex: '8', width: '186px', background: '#16302c', borderRadius: '26px', padding: '8px', boxShadow: '0 40px 78px -24px rgba(15,23,41,.5)', animation: 'floatY2 7.5s ease-in-out infinite'}}>
                <div style={{background: '#f4f8f7', borderRadius: '19px', overflow: 'hidden'}}>
                  <div style={{display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '6px 11px 4px', fontSize: '7.5px', fontWeight: '700', color: '#0f1729'}}><span>9:41</span><span>▪▪▪ ▪ ◔</span></div>
                  <div style={{display: 'flex', alignItems: 'center', gap: '6px', padding: '4px 10px 8px', background: '#fff'}}><span style={{display: 'flex', flexDirection: 'column', gap: '2px'}}><span style={{width: '11px', height: '1.6px', background: '#39404d'}}></span><span style={{width: '11px', height: '1.6px', background: '#39404d'}}></span><span style={{width: '11px', height: '1.6px', background: '#39404d'}}></span></span><span style={{flex: '1', display: 'flex', alignItems: 'center', gap: '4px', border: '1px solid #d3e6e2', borderRadius: '99px', padding: '4px 8px'}}><svg width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="#0e9384" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="8" r="4"></circle><path d="M4 21a8 8 0 0 1 16 0"></path></svg><span style={{fontSize: '8px', fontWeight: '600', color: '#0f1729'}}>{t("Rehan Dilawar")}</span><span style={{marginInlineStart: 'auto', fontSize: '6px', color: '#657085'}}>▾</span></span><span style={{width: '16px', height: '16px', borderRadius: '50%', background: '#0e9384', color: '#fff', display: 'grid', placeItems: 'center', fontSize: '7px'}}>◔</span></div>
                  <div style={{background: '#fff', margin: '8px 9px 0', border: '1px solid #eaf1f0', borderRadius: '13px', padding: '9px 10px'}}>
                    <div style={{display: 'flex', alignItems: 'center'}}><span style={{fontSize: '8px', color: '#0e9384'}}>‹</span><span style={{flex: '1', textAlign: 'center', fontSize: '10px', fontWeight: '700', color: '#0f1729'}}>{t("July 2026")}</span><span style={{fontSize: '8px', color: '#0e9384'}}>›</span></div>
                    <div style={{display: 'grid', gridTemplateColumns: 'repeat(7,1fr)', gap: '1px', textAlign: 'center', marginTop: '5px'}}>
                      <span style={{fontSize: '6px', color: '#657085'}}>{t("Sun")}</span><span style={{fontSize: '6px', color: '#657085'}}>{t("Mon")}</span><span style={{fontSize: '6px', color: '#657085'}}>{t("Tue")}</span><span style={{fontSize: '6px', color: '#657085'}}>{t("Wed")}</span><span style={{fontSize: '6px', color: '#657085'}}>{t("Thu")}</span><span style={{fontSize: '6px', color: '#657085'}}>{t("Fri")}</span><span style={{fontSize: '6px', color: '#657085'}}>{t("Sat")}</span>
                      <span style={{fontSize: '7.5px', color: '#c3cad6', padding: '3px 0'}}>28</span><span style={{fontSize: '7.5px', color: '#c3cad6', padding: '3px 0'}}>29</span><span style={{fontSize: '7.5px', color: '#c3cad6', padding: '3px 0'}}>30</span>
                      <span style={{position: 'relative', fontSize: '7.5px', padding: '3px 0'}}><span style={{position: 'absolute', inset: '1px 2px', background: '#0e9384', borderRadius: '50%', opacity: '.35', animation: 'calTrace 4s ease-in-out infinite'}}></span><span style={{position: 'relative', color: '#0f1729', fontWeight: '700'}}>1</span></span>
                      <span style={{position: 'relative', fontSize: '7.5px', padding: '3px 0'}}><span style={{position: 'absolute', inset: '1px 2px', background: '#0e9384', borderRadius: '50%', opacity: '.35', animation: 'calTrace 4s ease-in-out .4s infinite'}}></span><span style={{position: 'relative', color: '#0f1729', fontWeight: '700'}}>2</span></span>
                      <span style={{position: 'relative', fontSize: '7.5px', padding: '3px 0'}}><span style={{position: 'absolute', inset: '1px 2px', background: '#0e9384', borderRadius: '50%', animation: 'calSel 4s ease-in-out infinite'}}></span><span style={{position: 'relative', color: '#fff', fontWeight: '700'}}>3</span></span>
                      <span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0'}}>4</span>
                      <span style={{fontSize: '7.5px', color: '#c3cad6', padding: '3px 0', position: 'relative'}}>5</span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0', position: 'relative'}}>6<span style={{position: 'absolute', bottom: '1px', insetInlineStart: '50%', width: '3px', height: '3px', marginInlineStart: '-1.5px', borderRadius: '50%', background: '#2f6fe4'}}></span></span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0', position: 'relative'}}>7</span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0', position: 'relative'}}>8<span style={{position: 'absolute', bottom: '1px', insetInlineStart: '50%', width: '3px', height: '3px', marginInlineStart: '-1.5px', borderRadius: '50%', background: '#2f6fe4'}}></span></span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0', position: 'relative'}}>9</span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0', position: 'relative'}}>10</span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0', position: 'relative'}}>11</span>
                      <span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0', position: 'relative'}}>12</span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0', position: 'relative'}}>13</span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0', position: 'relative'}}>14<span style={{position: 'absolute', bottom: '1px', insetInlineStart: '50%', width: '3px', height: '3px', marginInlineStart: '-1.5px', borderRadius: '50%', background: '#2f6fe4'}}></span></span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0', position: 'relative'}}>15</span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0', position: 'relative'}}>16</span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0', position: 'relative'}}>17</span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0', position: 'relative'}}>18</span>
                      <span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0', position: 'relative'}}>19</span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0', position: 'relative'}}>20</span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0', position: 'relative'}}>21<span style={{position: 'absolute', bottom: '1px', insetInlineStart: '50%', width: '3px', height: '3px', marginInlineStart: '-1.5px', borderRadius: '50%', background: '#2f6fe4'}}></span></span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0', position: 'relative'}}>22</span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0', position: 'relative'}}>23</span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0', position: 'relative'}}>24</span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0', position: 'relative'}}>25</span>
                      <span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0'}}>26</span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0'}}>27</span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0'}}>28</span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0'}}>29</span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0'}}>30</span><span style={{fontSize: '7.5px', color: '#4b5565', padding: '3px 0'}}>31</span>
                    </div>
                  </div>
                  <div style={{display: 'flex', background: '#fff', margin: '7px 9px 0', border: '1px solid #eaf1f0', borderRadius: '11px', padding: '7px 3px', textAlign: 'center'}}>
                    <span style={{flex: '1'}}><span style={{display: 'block', fontSize: '11px', fontWeight: '800', color: '#2f6fe4'}}>2</span><span style={{display: 'block', fontSize: '5.5px', color: '#657085'}}>{t("Planned")}</span></span><span style={{flex: '1'}}><span style={{display: 'block', fontSize: '11px', fontWeight: '800', color: '#157d44'}}>1</span><span style={{display: 'block', fontSize: '5.5px', color: '#657085'}}>{t("Completed")}</span></span><span style={{flex: '1'}}><span style={{display: 'block', fontSize: '11px', fontWeight: '800', color: '#e5484d'}}>0</span><span style={{display: 'block', fontSize: '5.5px', color: '#657085'}}>{t("Deferred")}</span></span><span style={{flex: '1'}}><span style={{display: 'block', fontSize: '11px', fontWeight: '800', color: '#926702'}}>1</span><span style={{display: 'block', fontSize: '5.5px', color: '#657085'}}>{t("Unplanned")}</span></span><span style={{flex: '1'}}><span style={{display: 'block', fontSize: '11px', fontWeight: '800', color: '#0f1729'}}>1</span><span style={{display: 'block', fontSize: '5.5px', color: '#657085'}}>{t("Total")}</span></span>
                  </div>
                  <div style={{fontSize: '7.5px', fontWeight: '700', color: '#0f1729', margin: '8px 11px 0'}}>{t("Thursday, July 3")} <span style={{fontWeight: '400', color: '#657085'}}>{t("· 3 calls")}</span></div>
                  <div style={{background: '#fff', margin: '4px 9px 9px', border: '1px solid #eaf1f0', borderRadius: '12px', padding: '9px 10px'}}>
                    <div style={{display: 'flex', alignItems: 'center', gap: '6px'}}><span style={{width: '20px', height: '20px', borderRadius: '50%', background: '#0e9384', color: '#fff', display: 'grid', placeItems: 'center', fontSize: '7.5px', fontWeight: '700'}}>SB</span><span style={{flex: '1'}}><span style={{display: 'block', fontSize: '8.5px', fontWeight: '700', color: '#0f1729'}}>{t("Dr. Sana Bukhari")}</span><span style={{display: 'block', fontSize: '6.5px', color: '#657085'}}>{t("Face-to-Face · CDA")}</span></span><span style={{fontSize: '6px', fontWeight: '700', color: '#2f6fe4', background: '#e8effc', borderRadius: '99px', padding: '2px 7px'}}>{t("◷ Planned")}</span></div>
                    <div style={{fontSize: '6.5px', color: '#5b6472', marginTop: '5px'}}>◷ 11:30 AM</div>
                    <div style={{display: 'flex', gap: '3px', marginTop: '5px', flexWrap: 'wrap'}}><span style={{fontSize: '6px', fontWeight: '700', color: '#0e9384', background: '#e0f2ef', borderRadius: '99px', padding: '2px 7px'}}>CARDIVEX</span><span style={{fontSize: '6px', fontWeight: '700', color: '#0e9384', background: '#e0f2ef', borderRadius: '99px', padding: '2px 7px'}}>NEUROZA</span><span style={{fontSize: '6px', fontWeight: '700', color: '#0e9384', background: '#e0f2ef', borderRadius: '99px', padding: '2px 7px'}}>PAZORENE</span></div>
                  </div>
                  <div style={{display: 'flex', justifyContent: 'space-around', padding: '5px 0 6px', borderTop: '1px solid #eaf1f0', background: '#fff'}}>
                    <span style={{fontSize: '6.5px', color: '#657085', textAlign: 'center'}}>⌂<br />{t("Home")}</span><span style={{fontSize: '6.5px', color: '#0e9384', fontWeight: '700', textAlign: 'center'}}>≣<br />{t("Call List")}</span><span style={{fontSize: '6.5px', color: '#657085', textAlign: 'center'}}>🔔<br />{t("Alerts")}</span>
                  </div>
                </div>
              </div>
            </div>
    </>
  );
}